/*! Copyright 2013 Baidu Inc. All RightsReserved. */;(function(){var baidu=(function(){var T,baidu=T=baidu||{version:"1.5.2"};baidu.guid="$BAIDU$";baidu.$$=window[baidu.guid]=window[baidu.guid]||{global:{}};baidu.dom=baidu.dom||{};baidu.dom.g=function(a){if(!a){return null}if("string"==typeof a||a instanceof String){return document.getElementById(a)}else{if(a.nodeName&&(a.nodeType==1||a.nodeType==9)){return a}}return null};baidu.g=baidu.G=baidu.dom.g;baidu.dom._styleFixer=baidu.dom._styleFixer||{};baidu.dom._styleFilter=baidu.dom._styleFilter||[];baidu.dom._styleFilter.filter=function(b,e,f){for(var a=0,d=baidu.dom._styleFilter,c;c=d[a];a++){if(c=c[f]){e=c(b,e)}}return e};baidu.string=baidu.string||{};baidu.string.toCamelCase=function(a){if(a.indexOf("-")<0&&a.indexOf("_")<0){return a}return a.replace(/[-_][^-_]/g,function(b){return b.charAt(1).toUpperCase()})};baidu.dom.setStyle=function(c,b,d){var e=baidu.dom,a;
c=e.g(c);b=baidu.string.toCamelCase(b);if(a=e._styleFilter){d=a.filter(b,d,"set")}a=e._styleFixer[b];(a&&a.set)?a.set(c,d):(c.style[a||b]=d);return c};baidu.setStyle=baidu.dom.setStyle;baidu.dom.setStyles=function(b,c){b=baidu.dom.g(b);for(var a in c){baidu.dom.setStyle(b,a,c[a])}return b};baidu.setStyles=baidu.dom.setStyles;baidu.browser=baidu.browser||{};(function(){var a=navigator.userAgent;baidu.browser.safari=/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(a)&&!/chrome/i.test(a)?+(RegExp["\x241"]||RegExp["\x242"]):undefined})();baidu.browser.ie=baidu.ie=/msie (\d+\.\d+)/i.test(navigator.userAgent)?(document.documentMode||+RegExp["\x241"]):undefined;baidu.browser.opera=/opera(\/| )(\d+(\.\d+)?)(.+?(version\/(\d+(\.\d+)?)))?/i.test(navigator.userAgent)?+(RegExp["\x246"]||RegExp["\x242"]):undefined;
(function(){var a=baidu.dom.ready=function(){var g=false,f=[],c;if(document.addEventListener){c=function(){document.removeEventListener("DOMContentLoaded",c,false);d()}}else{if(document.attachEvent){c=function(){if(document.readyState==="complete"){document.detachEvent("onreadystatechange",c);d()}}}}function d(){if(!d.isReady){d.isReady=true;for(var k=0,h=f.length;k<h;k++){f[k]()}}}function b(){try{document.documentElement.doScroll("left")}catch(h){setTimeout(b,1);return}d()}function e(){if(g){return}g=true;if(document.readyState==="complete"){d.isReady=true}else{if(document.addEventListener){document.addEventListener("DOMContentLoaded",c,false);window.addEventListener("load",d,false)}else{if(document.attachEvent){document.attachEvent("onreadystatechange",c);window.attachEvent("onload",d);var h=false;
try{h=window.frameElement==null}catch(i){}if(document.documentElement.doScroll&&h){b()}}}}}e();return function(h){d.isReady?h():f.push(h)}}();a.isReady=false})();baidu.event=baidu.event||{};baidu.event._listeners=baidu.event._listeners||[];baidu.lang=baidu.lang||{};baidu.lang.isString=function(a){return"[object String]"==Object.prototype.toString.call(a)};baidu.isString=baidu.lang.isString;baidu.dom._g=function(a){if(baidu.lang.isString(a)){return document.getElementById(a)}return a};baidu._g=baidu.dom._g;baidu.event.on=function(b,e,g){e=e.replace(/^on/i,"");b=baidu.dom._g(b);var f=function(i){g.call(b,i)},a=baidu.event._listeners,d=baidu.event._eventFilter,h,c=e;e=e.toLowerCase();if(d&&d[e]){h=d[e](b,e,f);c=h.type;f=h.listener}if(b.addEventListener){b.addEventListener(c,f,false)}else{if(b.attachEvent){b.attachEvent("on"+c,f)
}}a[a.length]=[b,e,g,f,c];return b};baidu.on=baidu.event.on;baidu.fn=baidu.fn||{};baidu.fn.bind=function(b,a){var c=arguments.length>2?[].slice.call(arguments,2):null;return function(){var e=baidu.lang.isString(b)?a[b]:b,d=(c)?c.concat([].slice.call(arguments,0)):arguments;return e.apply(a||e,d)}};baidu.browser.chrome=/chrome\/(\d+\.\d+)/i.test(navigator.userAgent)?+RegExp["\x241"]:undefined;baidu.fn.blank=function(){};baidu.dom.contains=function(a,b){var c=baidu.dom._g;a=c(a);b=c(b);return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};baidu.dom.hide=function(a){a=baidu.dom.g(a);a.style.display="none";return a};baidu.hide=baidu.dom.hide;baidu.dom.show=function(a){a=baidu.dom.g(a);a.style.display="";return a};baidu.show=baidu.dom.show;baidu.object=baidu.object||{};baidu.extend=baidu.object.extend=function(c,a){for(var b in a){if(a.hasOwnProperty(b)){c[b]=a[b]
}}return c};baidu.url=baidu.url||{};baidu.string.escapeReg=function(a){return String(a).replace(new RegExp("([.*+?^=!:\x24{}()|[\\]/\\\\])","g"),"\\\x241")};baidu.url.getQueryValue=function(b,c){var d=new RegExp("(^|&|\\?|#)"+baidu.string.escapeReg(c)+"=([^&#]*)(&|\x24|#)","");var a=b.match(d);if(a){return a[2]}return null};baidu.lang.isArray=function(a){return"[object Array]"==Object.prototype.toString.call(a)};baidu.lang.isFunction=function(a){return"[object Function]"==Object.prototype.toString.call(a)};baidu.lang.toArray=function(b){if(b===null||b===undefined){return[]}if(baidu.lang.isArray(b)){return b}if(typeof b.length!=="number"||typeof b==="string"||baidu.lang.isFunction(b)){return[b]}if(b.item){var a=b.length,c=new Array(a);while(a--){c[a]=b[a]}return c}return[].slice.call(b)};baidu.event.un=function(c,f,b){c=baidu.dom._g(c);
f=f.replace(/^on/i,"").toLowerCase();var i=baidu.event._listeners,d=i.length,e=!b,h,g,a;while(d--){h=i[d];if(h[1]===f&&h[0]===c&&(e||h[2]===b)){g=h[4];a=h[3];if(c.removeEventListener){c.removeEventListener(g,a,false)}else{if(c.detachEvent){c.detachEvent("on"+g,a)}}i.splice(d,1)}}return c};baidu.un=baidu.event.un;baidu.array=baidu.array||{};baidu.each=baidu.array.forEach=baidu.array.each=function(g,e,b){var d,f,c,a=g.length;if("function"==typeof e){for(c=0;c<a;c++){f=g[c];d=e.call(b||g,f,c);if(d===false){break}}}return g};baidu.dom.getDocument=function(a){a=baidu.dom.g(a);return a.nodeType==9?a:a.ownerDocument||a.document};baidu.dom.getComputedStyle=function(b,a){b=baidu.dom._g(b);var d=baidu.dom.getDocument(b),c;if(d.defaultView&&d.defaultView.getComputedStyle){c=d.defaultView.getComputedStyle(b,null);
if(c){return c[a]||c.getPropertyValue(a)}}return""};baidu.dom.getStyle=function(c,b){var e=baidu.dom;c=e.g(c);b=baidu.string.toCamelCase(b);var d=c.style[b]||(c.currentStyle?c.currentStyle[b]:"")||e.getComputedStyle(c,b);if(!d){var a=e._styleFixer[b];if(a){d=a.get?a.get(c):baidu.dom.getStyle(c,a)}}if(a=e._styleFilter){d=a.filter(b,d,"get")}return d};baidu.getStyle=baidu.dom.getStyle;baidu.event._eventFilter=baidu.event._eventFilter||{};baidu.event._eventFilter._crossElementBoundary=function(a,d){var c=d.relatedTarget,b=d.currentTarget;if(c===false||b==c||(c&&(c.prefix=="xul"||baidu.dom.contains(b,c)))){return}return a.call(b,d)};baidu.event._eventFilter.mouseenter=window.attachEvent?null:function(a,b,c){return{type:"mouseover",listener:baidu.fn.bind(baidu.event._eventFilter._crossElementBoundary,this,c)}
};baidu.event._eventFilter.mouseleave=window.attachEvent?null:function(a,b,c){return{type:"mouseout",listener:baidu.fn.bind(baidu.event._eventFilter._crossElementBoundary,this,c)}};; return baidu;})();var j=void 0,k=!0,l=null,m=!1,n={},ba="1",o="0",p=document,r=p.body,ca="CSS1Compat"!==p.compatMode,s=ca?r:p.documentElement,u=window.BAIDU_CLB_SLOTS_MAP,da=window.BAIDU_DAN_config||{},ea=100,fa=100,v=2147483647,ha=-2147483648,ia=Object.prototype.hasOwnProperty,A=o,ka="data-baidu-dan-id",B="data-baidu-dan-position-fix",la="data-baidu-dan-player-toggle-state",ma=0,na={N:"http://pplmauth.baidu.com/cpro/auth/authorizer.php",E:"http://epplmauth.baidu.com/cpro/auth/authorizer.php"};
na["gmvl.baidu.com"]=na.N;var C={N:"http://gmvl.baidu.com/dan/sp.html",E:"http://egmvl.baidu.com/dan/sp.html"};C["gmvl.baidu.com"]=C.N;
var oa="http://cpro.baidustatic.com/cpro/ui/y.js",pa="http://dn.baidu.com/images/logo_h.gif",qa="http://hong.baidu.com/",ra="0",sa="1",ta="2",Aa={close:{text:"\u5173\u95ed",width:16,height:16,offsetX:0,offsetY:0,Y:"http://img.baidu.com/adm/control.gif",V:ua},minimize:{text:"\u6700\u5c0f\u5316",width:16,height:16,offsetX:-16,offsetY:0,Y:"http://img.baidu.com/adm/control.gif",V:va}},Ba={"0":"video",1:"video",2:"barrier",3:"null",4:"static",5:"static",6:"video",7:"float",8:"null",20:"video",21:"video",
22:"couplet",23:"barrier",24:"static",25:"expand",26:"null",27:"captcha"},E={"0":"video",1:"video",2:"flash",3:"image",4:"null",5:"video",6:"video",7:"flash",8:"flash",20:"video",21:"flash",22:"image",23:"media"},F=l,Ca;function G(a,b,d){a.setAttribute(b,d)}var Da=m,H=p.createElement("div"),I=p.createElement("div");H.style.position="absolute";H.style.top="200px";I.style.position="fixed";I.style.top="100px";H.appendChild(I);r.appendChild(H);
I.getBoundingClientRect&&I.getBoundingClientRect().top==H.getBoundingClientRect().top&&(F={});r.removeChild(H);(function(){var a=p.createElement("object");"classid"in a&&(Da=k,a.setAttribute("test","test"),a.getAttribute("test")||(G=function(a,d,c){a[d]=c}))})();var Ea=p.createElement("div");Ea.innerHTML='<div style="opacity:.25;"></div>';Ca="0.25"==Ea.firstChild.style.opacity;function J(a){return j===a?"":encodeURIComponent(a)}
function K(a){var a=a&&a.style,b=0,d=0,c;if(F&&!ca&&(c=r.style.position||(r.currentStyle?r.currentStyle.position:""),"relative"===c||"absolute"===c))b=r.offsetLeft||0,d=r.offsetTop||0;a&&(a.top="0",a.left="0");return{width:s.clientWidth,height:s.clientHeight,scrollLeft:window.pageXOffset||s.scrollLeft,scrollTop:window.pageYOffset||s.scrollTop,h:b,l:d}}
function L(a){var b=new Image,d="baidu_dan_log_"+ +new Date;window[d]=b;b.onload=b.onerror=b.onabort=function(){try{delete window[d]}catch(a){window[d]=j}b=l};a+=-1<a.indexOf("?")?"&":"?";a+=".stamp="+Math.random();b.src=a}
function Fa(){var a=p.domain;0===a.indexOf("www.")&&(a=a.substr(4));"."===a.charAt(a.length-1)&&(a=a.substring(0,a.length-1));var b=a.match(RegExp("([a-z0-9][a-z0-9\\-]*?\\.(?:com|cn|net|org|gov|info|la|cc|co|jp|us|hk|tv|me|biz|in|be|io|tk|cm|li|ru|ws|hn|fm)(?:\\.(?:cn|jp|tw|ru))?)$","i"));return b?b[0]:a}function Ga(a){a=escape(a).replace(/([*+-.\/@_])/g,function(a){return"%"+a.charCodeAt(0).toString(16)});return a.replace(/%/g,"_")}
function Ha(a,b){var d=b||l,c=p.createElement("script");c.charset="utf-8";c.async=k;c.src=a;if(d){var e=m;c.onload=c.onreadystatechange=function(){if(!e&&(!c.readyState||"loaded"===c.readyState||"complete"===c.readyState))e=k,d()}}var f=p.getElementsByTagName("head")[0]||p.body;f.insertBefore(c,f.firstChild)}
function Ia(){var a=window.pageXOffset||s.scrollLeft,b=window.pageYOffset||s.scrollTop,d=p.createElement("div");baidu.dom.setStyles(d,{position:"absolute",top:"0px",left:"0px"});r.appendChild(d);var c=d.getBoundingClientRect(),e={};e.top=c.top+b;e.left=c.left+a;r.removeChild(d);return e}
function Ja(a,b){var d=N(a);Ka(d);if(!d.B||!(0<(O&292))){var c=d.type;n[c]&&n[c].create&&baidu.dom.ready(function(){n[c].create(d,b)});d.U&&Ha(d.U);if(!d.placeholder&&b){var e=baidu.g(b);e&&e.parentNode.removeChild(e)}}}window.BAIDU_DAN_showAd=window.BAIDU_DAN_showAd||Ja;var La={};function Ma(a){var b=a.id;1!==La[b]&&(La[b]=1,a=N(b),Na(a),b=a.type,("video"!==b||"video"!==a.a)&&Oa(a),setTimeout(function(){Pa(a,"start")},0),n[b]&&n[b].show&&n[b].show(a))}
n.video=function(){function a(a){x=a;t&&(w=(+new Date-t)/1E3)}function b(a){L(C[a.p]+"?"+a.c+"&tm="+J(+new Date)+"&l="+w+"&m="+e+"&alp="+f+"&alr="+g+"&alrs="+h+"&alm="+q+"&allc="+z+"&alsc="+i+"&als="+y+"&tgs="+A+"&pt="+a.d)}function d(e,d){b(e);switch(d){case "start":clearInterval(c);x||(c=setInterval(function(){a(m);150<w?clearInterval(c):b(e)},5E3));break;case "stop":clearInterval(c)}}var c=0,e=0,f=0,g=0,h=0,q=0,z=0,i=0,y=0,t=0,w=0,x=m;return{create:function(a){if(!(0<ma++)){var b=a.id,c=a.width,
e=a.height,d=P(b,c,e),f=R(a,d);Qa(f,b,c,e);F&&G(d,B,2);r.appendChild(f);S(d,a);baidu.dom.setStyle(f,"z-index",ha)}},show:function(a){"video"===a.type&&"video"===a.a&&(t=+new Date,d(a,"start"));a=baidu.g(T(a.id));baidu.dom.setStyle(a,"z-index",v);F&&U()},L:function(b,c,f){"video"===f.type&&"video"===f.a&&(e++,x||(a(k),d(f,"stop")))},ma:function(){return w},ya:function(c){x||(a(m),b(c))},za:function(b){x||(a(k),d(b,"stop"))},ua:function(a){f++;b(a)},va:function(a){g++;b(a)},wa:function(a){h++;b(a)},
ta:function(a){q++;b(a)},sa:function(a){z++;b(a)},ra:function(a){i++;b(a)},xa:function(a){y++;b(a)}}}();
n.barrier=function(){function a(a){d=setTimeout(function(){va(a)},a.aa)}function b(){d&&clearTimeout(d)}var d=0;return{create:function(a){if(!(0<ma++)){var b=a.id,d=a.width,g=a.height,h=p.createElement("div"),q=P(b,d,g),z=p.createElement("div"),i=p.createElement("ins");i.id="baidu_dan_collapsed_"+b;i.style.display="block";baidu.event.on(i,"mouseover",baidu.fn.bind(Ra,i,N(b)));var y=Sa(a,"close"),t=R(a,[h,z]);baidu.browser.chrome&&(t.style.overflow="visible");z.style.display="none";h.appendChild(q);
z.appendChild(y);z.appendChild(i);baidu.dom.setStyles(t,{width:d+"px",height:g+16+"px"});V(t,b,1,0,d,g+16);baidu.dom.setStyle(t,"z-index",ha);F&&G(h,B,1);F&&G(z,B,3);r.appendChild(t);S(q,a);b={src:a.ga,width:ea,height:fa};a=parseInt(a.ha,10);(a=Ta[E[20>a?a+21:a]])&&a(i,b,baidu.fn.blank)}},show:function(b){var d=baidu.g(T(b.id));if(2>d.firstChild.children.length){var f=Sa(b,"minimize","close");d.firstChild.appendChild(f)}baidu.dom.setStyle(d,"z-index",v);F&&U();a(b)},fa:function(c,e,f){b();c=baidu.g(T(f.id));
c.style.height=N(c.getAttribute(ka)).height+16+"px";F||(e=c.style,e.bottom="auto",e.right="auto");V(c,j,1,0,f.width,f.height+16);d&&a(f)},L:function(a,b,d){a=baidu.g(T(d.id)).style;a.marginTop=0;a.marginLeft=0;a.height=fa+16+"px";a.top="auto";a.left="auto"},clear:b}}();
n["static"]={create:function(a,b){var d=baidu.g(b);if(d){var c=P(a.id,a.width,a.height),e=R(a,c),f=da.zIndex,f=0<parseInt(f,10)?f:v;baidu.dom.setStyle(e,"z-index",f);d.style.display="";d.appendChild(e);S(c,a);Ua(e,a)}},m:function(a){return{a:Xa(E[u[a]._html.material_type]),placeholder:k}}};
n.couplet=function(){function a(a,f,g,h,q,z){var i=p.createElement("div"),y=p.createElement("div"),t=R({id:a,width:d,height:c},[i,y]);baidu.browser.chrome&&(t.style.overflow="visible");f=P(a,f,g);g=p.createElement("div");g.id="baidu_dan_couplet_closeButton";baidu.on(g,"click",baidu.fn.bind(b,l,a,h));baidu.dom.setStyles(g,{position:"relative",left:"73px",top:"3px",width:"52px",height:"20px",cursor:"pointer",background:"url(http://dn.baidu.com/images/couplet.png) no-repeat 0px 0px"});baidu.dom.setStyles(i,
{border:"1px solid #cccccc",margin:"3px"});baidu.dom.setStyles(y,{height:"24px",borderTop:"1px solid #cccccc",background:"url(http://dn.baidu.com/images/couplet.png) repeat-x 0px -20px"});baidu.dom.setStyles(t,{border:"1px solid #cccccc",backgroundColor:"#f7f7f7",textAlign:"left",zIndex:ha});i.appendChild(f);y.appendChild(g);i=0;"right"===q&&(i=2);V(t,a,i,z,d,c);F&&G(y,B,5);r.appendChild(t);q="left"===q;S(f,{id:h.id,type:h.type,d:h.d,b:h.b,c:h.c,j:h.j,f:h.f,a:q?h.a:h.Ea,src:q?h.src:h.Da,width:q?h.width:
h.da,height:q?h.height:h.ca});Ua(y,{id:a,type:h.type})}function b(a,b){ua({id:a,type:b.type})}var d=128,c=303;return{create:function(b){function f(a){if(!a.Z)return 10;a=Math.floor((s.clientWidth-a.ia)/2)-a.width-10;return 0<=a?a:10}if(!(screen.width<=b.minWidth||0<ma++)){var g=f(b),h=b.id;a(h,b.width,b.height,b,"left",g);var q="right_"+h;a(q,b.da,b.ca,b,"right",g);if(b.Z)baidu.event.on(window,"resize",function(){setTimeout(function(){var a=f(b);V(baidu.g(T(h)),h,0,a,d,c);V(baidu.g(T(q)),q,2,a,d,
c)},0)})}},show:function(a){var b=baidu.g(T(a.id)),a=baidu.g(T(a.id,"right"));b&&baidu.dom.setStyle(b,"z-index",v);a&&baidu.dom.setStyle(a,"z-index",v);F&&U()},m:function(a){var a=u[a]._html,b=parseInt(a.content_width,10);if(!b||720>b)b=4095;return{a:Xa(E[a.material_type]),Z:1===a.position,ia:b,minWidth:a.min_resolution,Da:a.right_src,Ea:Xa(E[a.right_type]),da:a.right_width,ca:a.right_height}}}}();
n.expand=function(){function a(a,b,d){var e,f,w=g[d.id];if(w.D){var x=s.clientWidth,ga=s.clientHeight;f=window.pageXOffset||s.scrollLeft;e=window.pageYOffset||s.scrollTop;var D=a.getBoundingClientRect();e=e+D.top-h.top;f=f+D.left-h.left;var D=a.getBoundingClientRect(),$=g[d.id],Q=d.H-d.width,aa=d.r-d.height,M=g[d.id];M.C=M.R?D.top>ga-D.bottom?1:2:D.left>x-D.right?3:4;1===$.C&&(e-=aa);3===$.C&&(f-=Q);baidu.dom.setStyles(b,{position:"absolute",top:e+"px",left:f+"px",width:d.H+"px",height:d.r+"px"});
baidu.dom.setStyle(a,"visibility","hidden");baidu.dom.setStyles(b,{visibility:"visible",zIndex:v});w.X=+new Date;w.s=1;c(d,2)}else w.t&&(w.log.W=+new Date-w.t,c(d,1))}function b(a,b,c){g[a.id].s&&(c=c.relatedTarget||c.toElement,(!c||!baidu.dom.contains(b,c))&&d(a))}function d(a){var b=g[a.id];if(b.s){b.M=+new Date;b.log.ea=b.M-b.X;b.s=0;var b=baidu.g(T(a.id)),d=baidu.g(T(a.id,"expand"));baidu.dom.setStyle(b,"visibility","visible");baidu.dom.setStyles(d,{visibility:"hidden",zIndex:ha});c(a,3)}}function c(a,
b){var d=g[a.id],c=[0,0,0,0,0,0,0,0];c[b]=1;switch(b){case 0:c[4]=d.log.S;c[5]=d.log.$;break;case 1:c[6]=d.log.W;break;case 3:c[7]=d.log.ea}Ya(a,0,1,"",c.join(","))}function e(a){a.id=a.id.replace("expand_","");var b=g[a.id];b.F=+new Date;b.log.S=b.F-b.T;b.log.$=b.F-b.t;b.D=1;c(a,0)}function f(a){var b=g[a.id];if(!b.options){var d=a.b;d&&(d=Za(d,"e_1"));b.options={id:"expand_"+a.id,b:d,d:a.d,c:a.c,width:a.H,height:a.r,src:a.ka,a:a.la,f:a.f,fn:"onExpandLoad",k:"id="+a.id}}return b.options}var g={},
h=Ia();return{create:function(c,e){var i=c.id;g[i]={R:1,C:1,Fa:0,t:0,T:0,F:0,na:0,D:0,s:0,X:0,M:0,log:{S:0,$:0,W:0,ea:0}};i=g[i];c.height===c.r&&(i.R=0);n["static"].create(c,e);var i=f(c),h=P(i.id,i.width,i.height),h=R(i,h);baidu.dom.setStyles(h,{width:"0px",height:"0px",position:"absolute",top:"0px",left:"0px",zIndex:v});Ua(h,i);r.appendChild(h);i=baidu.g(T(c.id));h=baidu.g(T(c.id,"expand"));baidu.event.on(i,"mouseenter",baidu.fn.bind(a,l,i,h,c));baidu.event.on(h,"mouseleave",baidu.fn.bind(d,l,c));
baidu.event.on(i,"mouseleave",baidu.fn.bind(b,l,c,h))},show:function(a){var b=g[a.id];b.t=+new Date;b.na=1;setTimeout(function(){var c=f(a),d=baidu.g($a(c.id));b.T=+new Date;S(d,c,e)},5E3)},qa:e,m:function(a){a=u[a]._html;return{a:Xa(E[a.material_type]),ka:a.expand_src,la:Xa(E[a.expand_type]),H:a.expand_width,r:a.expand_height,placeholder:k}},Ga:function(a,b){var c=a.id;g[c].D&&(c="expand_"+c);setTimeout(function(){var a=baidu.g(W("logo_"+c));a.width=b.width;a.height=b.height},0)}}}();
n.captcha=function(){function a(){if(wa)i();else{var a=N(Q),b=baidu.g(T(a.id));"none"===b.style.display&&(V(b,a.id,1,0,xa,ya),F&&G(b.lastChild,B,1),e(a))}}function b(a){d(m);baidu.dom.hide(T(a.id))}function d(a){baidu.dom.setStyle(D,"display",a?"block":"none");baidu.dom.setStyles(ga,{"background-color":a?"#fef2f2":"","border-color":a?"#cc3333":"#cccccc"});baidu.dom.setStyle(x,"background-color",a?"#fef2f2":"")}function c(a){M=k;var b=q(a.id),c=baidu.g(x),e=encodeURIComponent(c.value);e?(Ha(na[a.p]+
"?"+("di="+a.id+"&ans="+e+"&jk="+b.Aa+"&fn="+t+"&dt="+(+new Date-aa))),za=setTimeout(function(){M=m;clearTimeout(za);h(a.id,m)},5E3)):(d(k),baidu.on(c,"keydown",f))}function e(a){M=m;aa=+new Date;var a="captcha=1&"+a.Ba,b={fn:w,dt:Math.round(+new Date/1E3)},c;for(c in b)ia.call(b,c)&&(a=a.replace(RegExp("&"+c+"=(\\w+)"),function(a,d){return a.replace(d,b[c])}));Ha("http://cb.baidu.com/ecom?"+a)}function f(){var a=baidu.g(x);baidu.un(a,"keydown",f);a.focus();a.value="";d(m)}function g(a){Va[a.id]=
a;var a=q(a.id),b=N(a.id);if(Wa&&(Wa=m,a.w&&b.P&&b.O)){z();wa=k;return}if(wa)i();else{b=baidu.g(T(b.id));baidu.dom.show(b);F&&U();f();b=baidu.g($a(a.id));baidu.dom.setStyles(b,{width:a.width+"px",height:a.height+"px"});b.innerHTML="";S(b,a,baidu.fn.blank);Oa(q(a.id));if(a.w){var c=a,d=document.createElement("div");baidu.dom.setStyles(d,{position:"absolute",left:"156px",bottom:"20px",width:"75px",height:"30px"});if(baidu.browser.ie&&8>parseInt(baidu.browser.ie,10))X(d,{id:c.id,width:"75",height:"30",
src:"http://dn.baidu.com/flash/captcha_vcode.swf",k:"img="+J(c.w)});else{var e=document.createElement("img");e.src="data:image/jpeg;base64,"+c.w;d.appendChild(e)}b.appendChild(d)}baidu.g($).innerHTML=a.Ca}}function h(a,c){if(M){var g=N(a),h=q(a);clearTimeout(za);if(c){if(baidu.g(x).value="",b(g),Na(h),"undefined"!==typeof window[y])window[y](c)}else h=baidu.g(x),e(g),aa=(new Date).getTime(),d(k),baidu.on(h,"keydown",f)}}function q(a){a=Va[a];return{id:a.id,width:a.width,height:a.height,d:a.product_type,
pa:a.material_type,a:E[a.material_type],src:a.src,j:a.monitor_url,Ca:unescape(a.question_tip),c:a.url_parameter,b:a.target_url,Aa:a.qid,w:a.verification_code,p:a._vlog}}function z(){var a=N(Q);window.ja&&(window.ja=l);Ha(oa,function(){window[qb]=window[y];var b={};b[a.P]={_html:"cpro_client=${cpro_client}|cpro_template=vcode_captchaF_254_218|cpro_h=185|cpro_w=250|cpro_at=image_flash|cpro_161=1|cpro_flush=4|cpro_cflush=#e10900|cpro_curl=#008000|cpro_cdesc=#444444|cpro_ctitle=#0000FF|cpro_cbg=#FFFFFF|cpro_cbd=#FFFFFF|cpro_cad=1".replace(/\$\{cpro_client\}/g,
a.O)};window[rb](b);i()})}function i(){var a=window[sb];a&&a()}var y="BAIDU_CLB_captchaVerifiedCallback",t="BAIDU_DAN_captchaAuthCallback",w="BAIDU_DAN_captchaMaterialCallback",x="baidu_dan_captcha_userInput",ga="baidu_dan_captcha_userInput_border",D="baidu_dan_captcha_errorInfo",$="baidu_dan_captcha_questionTip",Q=m,aa=+new Date,M=m,za=0,Va={},xa=330,ya=390;Ia();var Wa=k,wa=m,qb="fcallback_baiduCaptcha",sb="adDisplayHandler__baiduCaptcha",rb="BAIDU_CPRO_SETJSONADSLOT";window[w]=window[w]||g;window[t]=
window[t]||h;window.BAIDU_DAN_showCaptchaAd=window.BAIDU_DAN_showCaptchaAd||a;return{create:function(d){if(!Q){Q=d.id;var f=['<div style="position: absolute !important;width:'+xa+"px; height: "+ya+"px;overflow:hidden !important;background:url('http://dn.baidu.com/images/captcha.png') no-repeat scroll 0px 0px transparent; _filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, sizingMethod=none, src='http://dn.baidu.com/images/captcha.png');_background:none;\"></div>",'<div id="baidu_dan_captcha_innerWrapper" style="position:relative !important;text-align:left !important;width:310px;height:370px;top:10px;left:10px;font-size:12px;font-family: \'\u5b8b\u4f53,Arial\';"><div style="position: absolute ! important; right: 5px; top: 9px; height: 10px; width: 11px; cursor: pointer; " id="baidu_dan_captcha_closeButton"></div><div style="position: absolute ! important; left: 5px; top: 30px; width: 300px"><div id="baidu_dan_captcha_content" style="height: 250px; width: 300px;"></div><div style="height: 16px; margin-top: 10px; overflow: hidden; position: relative; width: 300px;">',
'<span id="'+$+'" style="line-height: 15px; color:#666666"></span>','<span style="line-height: 15px; color:#666666">\uff1a</span><span style="line-height: 15px; color:#666666; text-decoration:underline; cursor:pointer; margin-left:5px" id="baidu_dan_captcha_changeButton">\u6362\u4e00\u5f20</span></div><div style="overflow:hidden;*zoom:1;margin-top:9px;height:25px;vertical-align:middle;">','<div style="position:relative !important;float:left;height:23px;width:223px;border:1px solid #cccccc;" id="'+
ga+'">','<input type="text" style="margin-top:4px;padding:0px;line-height:16px;height:16px;margin-left:3px; border:0 none;width:218px;outline:none;" id="'+x+'">','<span style="position:absolute;line-height:16px;top:4px;right:0px;color:#cc3333;display:none" id="'+D+'">\u9519\u8bef\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165\uff01</span>','</div><div style="float:right;width:70px;height:25px;display:inline !important;cursor:pointer" id="baidu_dan_captcha_submit"></div></div><div style="height: 14px; line-height: 14px; margin-top: 8px; overflow: hidden;width: 300px;"><a style="color: #666666;" onfocus="this.blur()" href="mailto:yanzhengma@baidu.com" target="_blank">\u95ee\u9898\u53cd\u9988</a></div></div>'].join(""),
g=R(baidu.object.extend(d,{width:xa,height:ya}),[]);baidu.dom.setStyle(g,"display","none");baidu.dom.setStyle(g,"overflow","visible");g.innerHTML=f;r.appendChild(g);f=P(d.id,d.width||0,d.height||0);baidu.g("baidu_dan_captcha_content").appendChild(f);Ua(baidu.g("baidu_dan_captcha_innerWrapper"),d);baidu.on("baidu_dan_captcha_submit","click",baidu.fn.bind(c,l,d));baidu.on("baidu_dan_captcha_closeButton","click",baidu.fn.bind(b,l,d));baidu.on("baidu_dan_captcha_changeButton","click",baidu.fn.bind(e,
l,d));if(window.BAIDU_CLB_captchaBtnId&&baidu.g(window.BAIDU_CLB_captchaBtnId))baidu.on(window.BAIDU_CLB_captchaBtnId,"click",function(){a()})}},m:function(a){a=u[a]._html;return{O:a.cpro_client,P:a.cpro_id}}}}();function ua(a){var b=baidu.g(T(a.id));n[a.type].clear&&n[a.type].clear();b.style.display="none";setTimeout(function(){b.parentNode.removeChild(b)},0);Pa(a,"stop");return m}function T(a,b){return b?"baidu_dan_wrapper_"+b+"_"+a:"baidu_dan_wrapper_"+a}
function $a(a){return"baidu_dan_container_"+a}function W(a){return"baidu_dan_player_"+a}function Za(a,b){var d=baidu.url.getQueryValue(a,"k");d?(b="&k="+Ga(d+"|"+b),a=a.replace("&k="+d,b)):a=-1===a.indexOf("?")?a+"?k="+Ga(b):a+"&k="+Ga(b);return a}function P(a,b,d){var c=p.createElement("ins"),e=c.style;c.id=$a(a);e.display="block";e.width=b+"px";e.height=d+"px";e.position="relative";e.overflow="hidden";return c}
function R(a,b){var b=baidu.lang.toArray(b),d=a.id,c=p.createElement("ins"),e=c.style,f=0,g=b.length;c.id=T(d);c.setAttribute(ka,d);c.setAttribute(la,o);e.display="block";e.overflow="hidden";e.position="relative";e.textDecoration="none";e.zIndex=v;e.width=a.width+"px";for(e.height=a.height+"px";f<g;f++)c.appendChild(b[f]);return c}function S(a,b,d){var c=Ta[b.a];c&&c.apply(l,arguments)}
function X(a,b){var d=b.k||"id="+J(b.id);b.n&&(d+="&rcv_url="+J(b.f));a.innerHTML=Da?'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" name="baidu_dan_player" '+(b.id?'id="'+W(b.id)+'" ':"")+'width="'+b.width+'" height="'+b.height+'" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0"><param name="allowScriptAccess" value="always" /><param name="quality" value="high" /><param name="wmode" value="transparent" /><param name="movie" value="'+b.src+
'" />'+(d?'<param name="flashvars" value="'+d+'" />':"")+"</object>":'<embed wmode="transparent" src="'+b.src+'" quality="high" name="baidu_dan_player" '+(b.id?'id="'+W(b.id)+'" ':"")+(d?'flashVars="'+d+'" ':"")+'width="'+b.width+'" height="'+b.height+'"allowScriptAccess="always" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />';!b.n&&b.b&&ab(a,b.b)}
function ab(a,b){if(b){var d=p.createElement("a"),c=d.style;d.href=b;d.target="_blank";c.position="absolute";c.zIndex=999;c.top=0;c.width="100%";c.height="2000px";c.backgroundColor="#fff";Ca?c.opacity=0:(c.filter="alpha(opacity=0)",c.zoom=1);"outline"in c?c.outline="none":d.hideFocus=k;a.insertBefore(d,a.firstChild)}}
function Sa(a,b){var d=1,c=arguments.length,e,f,g=p.createElement("div");g.className="baidu-dan-control-bar";for(g.style.overflow="hidden";d<c;d++)e=arguments[d],e=Aa[e],f=p.createElement("span"),f.innerHTML=e.text,baidu.dom.setStyles(f,{width:e.width+"px",height:e.height+"px",backgroundImage:"url("+e.Y+")",backgroundPosition:e.offsetX+"px "+e.offsetY+"px",textIndent:"-2000px",overflow:"hidden",cssFloat:"right",styleFloat:"right"}),baidu.event.on(f,"click",baidu.fn.bind(e.V,f,a)),g.insertBefore(f,
g.firstChild);return g}
function Ua(a,b){var d;if("couplet"===b.type){d=document.createElement("a");d.id=T("logo_"+b.id);if(baidu.g(d.id))return;d.href=qa;d.target="_blank";var c={position:"absolute",zIndex:v,left:"5px",bottom:"3px",height:"17px",width:"12px",overflow:"hidden",background:"url("+pa+") no-repeat 0px 0px"},e=d.style;"outline"in e?e.outline="none":d.hideFocus=k;baidu.dom.setStyles(d,c)}else{d=document.createElement("div");d.id=T("logo_"+b.id);if(baidu.g(d.id))return;c={position:"absolute",zIndex:v,bottom:"0px",
height:"23px",right:"4px"};baidu.dom.setStyles(d,c);c="logo_"+b.id;X(d,{id:c,width:"18",height:"23",src:"http://dn.baidu.com/flash/logo_h.swf",k:(b.k||"id="+b.id)+"&logoId="+c})}a.appendChild(d)}
var Ta={video:function(a,b){X(a,{id:b.id,width:b.width,height:b.height,src:b.ba,k:["player_id="+J(b.id),"play_url="+J(b.src),"target_url="+J(b.b),"rcv_url="+J(b.f),"effect_time="+(b.aa/1E3).toFixed(),"o_mute="+(da.videoMute?"1":"0"),"o_volume="+("number"==typeof da.videoVolume?da.videoVolume:"20")].join("&")})},flash:X,image:function(a,b,d){var c=p.createElement("img");c.width=b.width;c.height=b.height;c.src=b.src;c.id=W(b.id);"function"!==typeof d?c.complete?Ma(b):c.onload=function(){c.onload=l;
Ma(b)}:d(b);c.style.display="block";a.appendChild(c);ab(a,b.b)},media:function(a,b){b.n=k;X(a,b)},shell:function(a,b){var d=b.src,c=b.fn||"onLoad",e=b.id,e=e.replace("expand_","");X(a,{id:e,src:"http://dn.baidu.com/flash/shell.swf",k:["id="+J(e),"fn="+J(c),"src="+J(d)].join("&"),n:b.n,f:b.f,width:b.width,height:b.height,b:b.b})}};
function va(a){var b=baidu.g(T(a.id)),d=b.firstChild,c=b.lastChild,e=b.style;setTimeout(function(){e.width=ea+"px";e.height=fa+"px";A=ba;b.setAttribute(la,A);var f=n[a.type].L&&n[a.type].L(d,c,a);"barrier"===a.type?V(b,a.id,2,0,j,j):Qa(b,a.id);!f&&d!==c&&(d.style.display="none",c.style.display="block");Pa(a,"stop")},0);return m}
function Ra(a){var b=baidu.g(T(a.id)),d=b.style,c=a.height,e=b.firstChild,f=b.lastChild;d.width=a.width+"px";d.height=c+"px";A=o;b.setAttribute(la,A);if((!n[a.type].fa||!n[a.type].fa(e,f,a))&&e!==f)f.style.display="none",e.style.display="block";F&&(e.getAttribute(B)||delete F[a.id],U());return m}
var N=function(){var a={};return function(b,d){if(!a[b]){var c=d||u[b],e=c._html;a[b]={id:b,Ia:c._w,Ha:c._h,c:e.url_parameter,d:e.product_type,type:Ba[e.product_type],pa:e.material_type,a:E[e.material_type],src:e.src,width:parseInt(e.width,10),height:parseInt(e.height,10),ba:e.player_url||"http://img.baidu.com/adm/video-player.swf",ha:e.collapse_type,ga:e.collapse_src||"http://img.baidu.com/adm/gm-logo-100x100.png",n:1==e.product_type||21==e.product_type,b:e.target_url,aa:1E3*e.max_impression_time||
5E3,f:e.rcv_url,j:e.monitor_url,B:"video"===Ba[e.product_type],Ba:e.query_string,p:c._vlog,U:e.extra_js};c=a[b].type;n[c].m&&baidu.object.extend(a[b],n[c].m(b))}return a[b]}}(),bb={};function Xa(a){return"flash"===a?"shell":a}
function V(a,b,d,c,e,f){var g=["left","center","right"];bb[b]={fixMode:d,marginOffset:c};e?baidu.dom.setStyles(a,{width:e+"px",height:f+"px"}):(e=a.offsetWidth,f=a.offsetHeight);F?(e=e||a.offsetWidth,g=f||a.offsetHeight,f=K(a),g={position:"absolute",top:f.scrollTop+(f.height-g)/2-f.l+"px"},0===d&&(g.left=f.scrollLeft-f.h+c+"px"),2===d&&(g.left=f.scrollLeft+f.width-f.h-e-c+"px"),1===d&&(g.left=f.scrollLeft-f.h+f.width/2+"px",g.marginLeft=(-(e/2)).toFixed()+"px"),baidu.dom.setStyles(a,g),b&&(F[b]=a)):
(b={position:"fixed",top:"50%",marginTop:(-(f/2)).toFixed()+"px"},1===d?(b.left="50%",b.marginLeft=(-(e/2)).toFixed()+"px"):b[g[d]]=c+"px",baidu.dom.setStyles(a,b))}function Qa(a,b,d,c){d?baidu.dom.setStyles(a,{width:d+"px",height:c+"px"}):(d=a.offsetWidth,c=a.offsetHeight);F?(cb(a,d,c),b&&(F[b]=a)):baidu.dom.setStyles(a,{position:"fixed",bottom:0,right:0})}
function cb(a,b,d){var b=b||a.offsetWidth,d=d||a.offsetHeight,c=K(a);baidu.dom.setStyles(a,{position:"absolute",left:c.scrollLeft+c.width-c.h-b+"px",top:c.scrollTop+c.height-c.l-d+"px"})}
var db=[l,function(a,b,d){var b=b||a.offsetWidth,d=d||a.offsetHeight,c=K(a);baidu.dom.setStyles(a,{position:"absolute",left:c.scrollLeft-c.h+c.width/2+"px",top:c.scrollTop-c.l+c.height/2+"px",marginLeft:(-(b/2)).toFixed()+"px",marginTop:(-(d/2)).toFixed()+"px"})},cb,function(a,b,d){var b=b||a.offsetWidth,d=d||a.offsetHeight,c=K(a);baidu.dom.setStyles(a,{position:"absolute",left:c.scrollLeft+c.width-c.h-b+"px",top:c.scrollTop-c.l+(c.height-d)/2+"px"})},function(a,b,d){d=d||a.offsetHeight;b=K(a);baidu.dom.setStyles(a,
{position:"absolute",left:b.scrollLeft-b.h+"px",top:b.scrollTop-b.l+(b.height-d)/2+"px"})},function(a,b,d,c){V(a,c,bb[c].fixMode,bb[c].marginOffset)}];
function U(){var a,b,d=0,c;for(a in F)ia.call(F,a)&&(d++,b=F[a],c=b.lastChild.offsetWidth?b.lastChild:b.firstChild,(c=c.getAttribute(B))&&function(a,b,c){setTimeout(function(){db[c](a,0,0,b)},0)}(b,a,c));0==d?(eb=m,baidu.event.un(window,"scroll",U),baidu.event.un(window,"resize",U)):eb||(eb=k,baidu.event.on(window,"scroll",U),baidu.event.on(window,"resize",U))}var eb=m;
function Na(a){var b=Fa();baidu.lang.isArray(a.j)&&a.j.length&&baidu.array.each(a.j,function(a){a=a.replace(/\{placement\}/g,b);L(a)})}function Oa(a){L(C[a.p]+"?"+a.c+"&tm="+J(+new Date)+"&pt="+J(a.d))}function Ya(a,b,d,c,e){a=N(a.id);L(C[a.p]+"?"+a.c+"&tm="+J(+new Date)+"&pt="+J(a.d)+"&ac="+(b+"|"+d+"|"+c+"|"+e))}function Y(a,b){var d=baidu.g(T(a)),c=Y[b];if(d&&c)return d=Array.prototype.slice.call(arguments),d[0]=N(a),d.splice(1,1),c.apply(l,d)}
window.BAIDU_DAN_materialCallback=window.BAIDU_DAN_materialCallback||Y;Y.onMinimize=va;Y.onRestore=Ra;Y.onClose=function(a){ua(a)};Y.onLoad=function(a){Ma(a)};Y.onExpandLoad=n.expand.qa;Y.onFinish=n.video.ya;Y.onPause=n.video.za;Y.logMousePause=n.video.ua;Y.logMouseReplay=n.video.va;Y.logMouseRestore=n.video.wa;Y.logMouseMute=n.video.ta;Y.logMouseMinimize=n.video.sa;Y.logMouseClose=n.video.ra;Y.logMouseSearch=n.video.xa;Y.openWindow=function(a,b){b&&b.url?window.open(b.url):Y.openClickUrl(a,{Ja:0})};
Y.openClickUrl=function(a,b){if(a.b){var d=0,c=a.b;baidu.url.getQueryValue(c,"k");b&&1===b.valid&&(d=1);c=Za(c,"v_"+d);b&&b.inField&&(c+="&in="+J(b.inField));window.open(c)}};Y.sendInteractiveLog=function(a,b){for(var d=b.name,c=0;c<d.length;c++)d[c]=J(d[c]);Ya(a,1,b.online,d.join(","),b.value.join(","))};Y.exposeAdElements=function(a){var b=baidu.g(T(a.id)),a=baidu.g(W(a.id));window.BAIDU_DAN_adElements={ins:b.firstChild,wrapper:b,swf:a}};
Y.resizeLogo=function(a,b){setTimeout(function(){var a=b.logoId,c=baidu.g(W(a)),a=baidu.g(T(a)).style;c.width=b.width;c.height=b.height;a.right=85===b.width?"0px":"4px"},0)};
Y.adInfo=function(a){var b,d,c,e,f;f=baidu.g(T(a.id));f.getBoundingClientRect?(f=f.getBoundingClientRect(),b=fb().document,e="CSS1Compat"!==b.compatMode?b.body:b.documentElement,b=e.clientHeight,d=e.clientWidth,c=e.clientLeft,e=e.clientTop,f.left>=c&&f.top>=e&&f.right<=d&&f.bottom<=b?(c=1,f.left<d/2&&(c|=1),f.top>b/2&&(c|=2),f=(2<c?c^1:c)+1):f=0):f=5;return[Fa(),a.id,baidu.url.getQueryValue(a.c,"mid"),a.width,a.height,f].join("|")};var Z={},gb=m,O=0,hb=0,ib=0;
function Pa(a,b){Z[a.id]||(Z[a.id]={K:"static"===a.type||"expand"===a.type,code:0,offsetX:0,offsetY:0,o:0,oa:12E3,count:0});var d=Z[a.id];"stop"===b&&clearInterval(d.o);"start"===b&&!d.o&&(jb(a),d.o=setInterval(function(){jb(a)},d.oa))}function jb(a){var b=Z[a.id];5<=b.count++?clearInterval(b.o):(kb(a,lb,function(a){a===m&&clearInterval(b.o)}),mb(a,b))}
function mb(a,b){L("http://cbjslog.baidu.com/dan_log?"+["ty="+ra,"di="+a.id,a.c,"pt="+a.d,"tgs="+(A||!b.K),"l="+n.video.ma(),"c="+b.code,"x="+b.offsetX,"y="+b.offsetY,"q="+(ca?1:0),"tm="+ +new Date].join("&"))}function kb(a,b,d){for(var c=k,e=0,f=b.length;e<f;e++)if(b[e]&&"function"===typeof b[e]&&b[e](a)===m){c=m;break}d&&d(c)}var vb=[nb,ob,pb,tb,ub],lb=[wb,xb,yb,zb];function nb(){return Ab()?(O|=1,k):m}function Ab(){return window!=window.top&&window!=window.parent?k:m}
function ob(){fb()!=window.top&&(O|=2)}function fb(){var a=Bb();return a[a.length-1]}function Bb(){for(var a=0,b=window,d=b.top,c=[b];b!==d&&10>a++&&Cb(b)&&Cb(b.parent);){b=b.parent;c.push(b)}Bb=function(){return c};return c}
function pb(a){for(var b=Bb(),d=window.top,c,e,f=0,g=b.length;f<g;f++){c=b[f];if(c===d)break;c=c.document;e=(e="CSS1Compat"!==c.compatMode)?c.body:c.documentElement;c=e.clientWidth;e=e.clientHeight;if(c<a.width||e<a.height)O|=4;c>2*a.width&&e>2*a.height&&(O|=8);100<c&&100<e&&(O|=16);if(28===(O&28))break}}function tb(){for(var a=Bb(),b,d=0,c=a.length-1;d<c;d++)if(b=a[d],!Db(b.frameElement)){O|=32;break}}
function Db(a){var b=baidu.dom.getStyle,d;if(!(d="none"==b(a,"display"))){if(!(b="hidden"==b(a,"visibility")))a=Ca?baidu.dom.getStyle(a,"opacity")||"1":(a=a.style.filter)&&0<=a.indexOf("opacity")?parseFloat(a.match(/opacity[=:]([^)]*)/)[1])/100+"":"1",b="1"!=a;d=b}return d?m:k}function ub(a){var b=Bb();2>b.length||(a=Eb(a,b[0].frameElement,a.B),a.u&&(hb=a.z,O|=64),a.v&&(ib=a.A,O|=128),a.I||(O|=256))}
function Eb(a,b,d){if(b.getBoundingClientRect){var c=b.getBoundingClientRect(),b=b.ownerDocument,e="CSS1Compat"!==b.compatMode?b.body:b.documentElement,f=e.clientHeight,g=e.clientWidth,b=e.clientLeft,e=e.clientTop;return d?(d=c.right-g-b,f=c.bottom-f-e,{u:1<Math.abs(d),v:1<Math.abs(f),z:d,A:f,J:c.left>=b&&c.top>=e&&1>=d&&1>=f,I:c.right-b>=a.width&&c.bottom-e>=a.height&&1>=d&&1>=f}):{u:m,v:m,z:c.left,A:c.top,J:c.left>=b&&c.top>=e&&c.right<=g&&c.bottom<=f,I:c.right-b>=a.width&&c.bottom-e>=a.height&&
g-c.left+b>=a.width&&f-c.top+e>=a.height}}L("http://cbjslog.baidu.com/dan_log?"+["ty="+ta,"url="+J(p.URL)].join("&"));return{u:m,v:m,z:0,A:0,J:k,I:k}}function wb(a){var b=Z[a.id],d=baidu.g(T(a.id)),c=baidu.g($a(a.id)),a=baidu.g(W(a.id));return!d||!c||!a?(b.code|=1,m):k}function xb(a){var b=Z[a.id];if(A===o||b.K){var d=baidu.g(W(a.id)),a=Eb(a,d,a.B);a.u&&(b.offsetX=a.z,b.code|=2);a.v&&(b.offsetY=a.A,b.code|=4);a.J||(b.code|=8)}}
function yb(a){for(var b=Z[a.id],d,c,e=baidu.g(W(a.id));e&&!(e===p||e===r||e===p.documentElement);e=e.parentNode){if(!Db(e)){b.code|=32;break}if(A===o||b.K)if(d=e.offsetWidth||e.clientWidth,c=e.offsetHeight||e.clientHeight,d<a.width&&"hidden"===baidu.dom.getStyle(e,"overflowX")||c<a.height&&"hidden"===baidu.dom.getStyle(e,"overflowY")){b.code|=16;break}}}
function zb(a){var b=Z[a.id],d=baidu.g(W(a.id)),c="video"===a.a?a.ba:a.src;if(Da&&"image"!==a.a)for(var e,a=0;a<d.childNodes.length;a++){if(e=d.childNodes[a],"movie"===e.getAttribute("name")&&(e=e.getAttribute("value"),e!=c&&"http://dn.baidu.com/flash/shell.swf"!=e)){b.code|=64;break}}else e=d.getAttribute("src"),e!=c&&"http://dn.baidu.com/flash/shell.swf"!=e&&(b.code|=64)}
function Ka(a){gb||(kb(a,vb),L("http://cbjslog.baidu.com/dan_log?"+["ty="+sa,"di="+a.id,a.c,"pt="+a.d,"if="+O,"x="+hb,"y="+ib,"ib="+(0<(O&292)?1:0),"ir="+J(Fb()),"tm="+ +new Date].join("&")),gb=k)}function Cb(a){var b=m;try{a&&"object"===typeof a&&a.document&&"setInterval"in a&&(b=k)}catch(d){b=m}return b}function Fb(){if(!Ab())return"";var a=fb();return a===window.top?a.document.location.href:a.document.referrer||a.document.location.href}var Gb=window.BAIDU_DAN_readySlotId;
if(Gb){Ja(Gb,"");0.01>Math.random()&&L("http://cbjslog.baidu.com/dan_log?"+["ty=4","di="+Gb,"url="+J(p.URL)].join("&"));try{delete window.BAIDU_DAN_readySlotId}catch(Hb){window.BAIDU_DAN_readySlotId=j}};})();