/*

  Includes:

  Sizzle CSS Selector Engine
  Copyright 2011, The Dojo Foundation
  Released under the MIT, BSD, and GPL Licenses.
  More information: http://sizzlejs.com/
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Copyright (c) 2013 VigLink. Rights reserved and patent(s) pending.
*/
(function(e){var d,c,l=function(a,i){try{return("function"===typeof window[i]||"object"===typeof window[i])&&a instanceof window[i]}catch(t){}return!1};c={_breaker:{},each:function(a,i){var t,b;if("object"===c.type(a)&&a.hasOwnProperty)for(t in a){if(a.hasOwnProperty(t)&&i(a[t],t)===c._breaker)break}else{t=0;for(b=a.length;t<b&&i(a[t],t)!==c._breaker;t++);}},extend:function(a){var i,t,b,c,g=arguments.length;a=a||{};for(t=1;t<g;t++)if(c=arguments[t],void 0!==c&&null!==c)for(b in c)i=c[b],a!==i&&void 0!==
i&&(a[b]=i);return a},noop:function(){},type:function(a){return null===a?"null":void 0===a?"undefined":l(a,"HTMLElement")||"object"===typeof a&&1===a.nodeType&&"string"===typeof a.nodeName?"element":l(a,"HTMLDocument")||"object"===typeof a&&("defaultView"in a||"parentWindow"in a)?"document":a==a.window?"window":Object.prototype.toString.call(a).slice(8,-1).toLowerCase()}};c.extend(c,{addClass:function(a,i){c.hasClass(a,i)||(a.className=(a.className?a.className+" ":"")+i)},attrValues:function(a,i,
b){return(i=a[i])?i.split(b||" "):[]},bind:function(a,i){return function(){return a.apply(i,arguments)}},browser:function(){var a={},i,b=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);c.each(b,function(b){i=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];a[i?b.substr(0,b.length-i.length-1).replace(/\d*$/,""):b]=i||!0});return{aol:a.aol,blackberry:a.blackberry,ie:a.msie,ios:a.mobile&&a.safari,opera:a.opera,playstation:a.playstation,
version:parseFloat(a.version||a.crios)||!1}}(),cache:function(){var a={},i="vglnk_"+(new Date).getTime(),b=0;return function(h,c,g){if(h){var d=h[i];if(d||void 0!==g)return d||(d=++b),a[d]||(h[i]=d,a[d]={}),void 0!==g&&(a[d][c]=g),"string"===typeof c?a[d][c]:a[d]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=c.createA(a));return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""},clone:function(a){return c.extend({},a)},contains:function(a,i){return-1!==
c.indexOf(a,i)},context:function(a){"element"===c.type(a)&&(a=a.ownerDocument);"document"===c.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===c.type(a))return a},containsPII:function(a){return/\b[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}\b/i.test(a)},contextIsAncestor:function(a,i){for(var b=a.self;b.parent&&b.parent!==b;)if(b=b.parent,b===i)return!0;return!1},cors:function(a){var i,b=function(){eval(i.responseText)};i=new window.XMLHttpRequest;i.onreadystatechange=function(){4===
i.readyState&&200===i.status&&b()};try{i.open("GET",a),i.withCredentials=!0,i.send()}catch(c){return!1}},createA:function(a,i){return c.createEl("a",{href:a,target:i})},createEl:function(a,i,b,h){var g;a=(h||document).createElement(a);i=i||{};b=b||{};for(g in i)void 0!==i[g]&&(a[g]=i[g]);c.css(a,b);return a},css:function(a,i){for(var b in i)try{a.style[b]=i[b]}catch(c){}return a},destructing:function(a){var i=!1,b;return function(){i||(b=a.apply(null,arguments),i=!0);return b}},escapeRegExp:function(){var a;
return function(i){a=a||RegExp("([.*+?^${}()|[\\]\\\\])","g");return i.replace(a,"\\$1")}}(),eventLink:function(a){var i,b=a.target||a.srcElement;do{try{i=b.nodeType}catch(c){break}if(1===i&&(a=b.tagName.toUpperCase(),"A"===a||"AREA"===a))return b;b=b.parentNode}while(b)},exceptionLogger:function(){var a=!1,i=c.noop;return function(b,c){if(void 0!==c)a=c,i=b;else return function(){if(a)try{return b.apply(this,arguments)}catch(c){i(c)}else return b.apply(this,arguments)}}}(),find:function(a,i){var b;
c.each(a,function(a,g){if(i(a,g))return b=a,c._breaker});return b},generateNodeFilter:function(){var a=function(a,i){var b,c;i=","+i.join(",")+",";b=0;for(c=a.length;b<c;b++)if(-1!==i.indexOf(","+a[b]+","))return!0;return!1},i=function(a,i){var b=a.nodeName.toLowerCase();return-1!==i.indexOf(","+b+",")};return function(b){b=c.extend({custom:null,classes:[],rels:[],tags:[]},b);b.tags.length&&(b.tags=","+b.tags.join(",").toLowerCase()+",");return function(g,k){k=c.extend({ancestors:!0,self:!0},k);var d=
!0,j=!0,f=function(g,h){var k;if(k=!(b.tags.length&&i(g,b.tags))){if(k=b.classes.length){k=b.classes;var d=c.attrValues(g,"className");k=a(k,d)}if(k=!k){if(k=b.rels.length)k=b.rels,d=c.attrValues(g,"rel"),k=i(g,",a,")&&a(k,d);k=!k&&!("function"===c.type(b.custom)&&b.custom(g,h))}}return k},j=!k.self||f(g,!0);if(k.ancestors)for(;g.parentNode;)if(g=g.parentNode,1===g.nodeType&&!f(g,!1)){d=!1;break}return j&&d}}}(),fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("\x26");var i={};
c.each(a,function(a){a=a.split("\x3d");i[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return i},geometry:function(){var a,i=arguments.length,b=Infinity,g=Infinity,k=-Infinity,d=-Infinity,j;for(a=0;a<i;a++)j=c.position(arguments[a]),b=Math.min(b,j.x),g=Math.min(g,j.y),k=Math.max(k,j.x+arguments[a].offsetWidth),d=Math.max(d,j.y+arguments[a].offsetHeight);return{x:b,y:g,w:k-b,h:d-g,x1:b,y1:g,x2:k,y2:d}},getActualHref:function(a){return c.cache(a,"href")||a.href},hasAttrValue:function(a,i,b,g){return i?
c.contains(c.attrValues(a,i,g),b):!1},hasClass:function(a,i){return c.hasAttrValue(a,"className",i)},hasRel:function(a,i){return c.hasAttrValue(a,"rel",i)},indexOf:Array.prototype.indexOf?function(a,i){return Array.prototype.indexOf.call(a,i)}:function(a,i){var b,g;b=0;for(g=a.length;b<g;b++)if(a[b]===i)return b;return-1},isArray:function(a){return"array"===c.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},jsonp:function(a){var i=
document.getElementsByTagName("script")[0];a=c.createEl("script",{type:"text/javascript",src:a});i.parentNode.insertBefore(a,i)},map:function(a,i){var b=[];c.each(a,function(a,g){void 0!==a&&(b[g]=i(a))});return b},on:function(){var a;return function(i,b,g){var k,d;if(1===arguments.length)a=i;else{if(2===arguments.length){if(!a)return;g=b;b=i;i=a}try{k=i["on"+b]}catch(j){}"function"===typeof k&&(i["on"+b]=c.bind(function(a){a=a||window.event;var b=k.apply(i,arguments);this.exceptionLogger(function(){return a?
(void 0!==b&&!1!==a.returnValue&&(a.returnValue=b),c.isDefaultPrevented(a)&&"function"===c.type(a.preventDefault)&&a.preventDefault(),a.returnValue):b})()},this));d=c.exceptionLogger(function(){if(a.enabled())return g.apply(null,arguments)});i.addEventListener?i.addEventListener(b,d,!1):i.attachEvent&&i.attachEvent("on"+b,d)}}}(),position:function(a){var b,g=0,c=0,k=0,d=0;if(!a.offsetParent)return!1;b=a;do g+=b.offsetLeft,c+=b.offsetTop,b=b.offsetParent;while(b);b=a;do k+=b.scrollLeft,d+=b.scrollTop,
b=b.parentNode;while(b&&b!==document.body);return{x:g-k,y:c-d}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},ready:function(){var a=!1,b=[],g=!1,h,k,d,j,f;document.addEventListener?d=function(){document.removeEventListener("DOMContentLoaded",d,!1);f()}:document.attachEvent&&(j=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",j),f())});h=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return f();
if(document.addEventListener)document.addEventListener("DOMContentLoaded",d,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",j);var b=!1;try{b=null===window.frameElement}catch(i){}document.documentElement.doScroll&&b&&k()}c.on(window,"load",f)}};k=function(){if(!g){try{document.documentElement.doScroll("left")}catch(a){setTimeout(c.exceptionLogger(k),1);return}f()}};f=function(){if(!g){if(!document.body)return setTimeout(c.exceptionLogger(f),13);g=!0;b&&(c.each(b,function(a){a()}),
b=null)}};return function(a){h();g?a():b.push(a)}}(),reformatKeys:function(a){var b,g,h=function(a){return"_"+a.toLowerCase()};for(b in a)g=b.replace(/([A-Z])/g,h),"object"===c.type(a[b])&&(a[b]=c.reformatKeys(a[b])),g!==b&&(a[g]=a[b],delete a[b]);return a},removeClass:function(a,b){if(c.hasClass(a,b)){var g,h,k=c.attrValues(a,"className");g=0;for(h=k.length;g<h;g++)k[g]===b&&delete k[g];a.className=k.join(" ")}},request:function(a,b,g){var h,k;g=c.extend({fn:c.noop,"return":!1,timeout:null},g);"string"===
typeof g.fn?b=c.extend(b,{jsonp:g.fn}):"function"===typeof g.fn&&(h=c.destructing(g.fn),k=c.uniqid("vglnk_jsonp_"),b=c.extend(b,{jsonp:k}),window[k]=c.exceptionLogger(function(){h.apply(this,arguments);window[k]=void 0}),null!==g.timeout&&setTimeout(c.exceptionLogger(h),g.timeout));b=c.extend({format:"jsonp"},b);b=c.toQuery(b);a=a+(b.length?"?":"")+b;return g["return"]?a:c.traits.cors&&!1!==c.cors(a)?!0:c.jsonp(a)},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,
0)}catch(b){var g,c,k=[];g=0;for(c=a.length;g<c;g++)k[g]=a[g];return k}},toQuery:function(a){var b,g="";for(b in a)null!==a[b]&&void 0!==a[b]&&(g+="\x26"+encodeURIComponent(b)+"\x3d"+encodeURIComponent(a[b]));return g.substr(1)},transmitsPII:function(a){return c.containsPII(a+" "+document.referrer)},updateUrl:function(a,b){return c.extend(c.createA(a),b).href},uniqid:function(){var a=0;return function(b){return(b||"")+(new Date).getTime()+a++}}()});c.traits={basicCompatibility:!(c.browser.blackberry||
c.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!c.browser.ios,jsRedirectSetsReferrer:c.browser.aol||!(c.browser.ie||c.browser.opera),quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var f,p,n,m=function(a){var b=a.previousSibling,g=a.nextSibling,h=["",a.textContent,""],k=function(a,b){for(var i=a,g=i.data;(i=i[b+"Sibling"])&&3===i.nodeType;)g+=i.data;return g},j=function(a,
b,i){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");i=i.replace(/\s+/g," ");a=a.replace(/^\s+/,"");" "===b.substr(0,1)&&(b=b.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===b.substr(b.length-1,1)&&(b=b.substr(0,b.length-1),i=(" "!==i.substr(0,1)?" ":"")+i);i=i.replace(/\s+$/,"");return[a,b,i]};void 0!==h[1]&&(h[0]=b&&3===b.nodeType?k(b,"previous"):"",h[2]=g&&3===g.nodeType?k(g,"next"):"",h=j.apply(this,h),""!==h[0]&&""!==h[2]&&(h[0]=h[0].split(" ").reverse().slice(0,10+(" "===h[0].substr(h[0].length-
1,1)?1:0)).reverse().join(" "),h[2]=h[2].split(" ").slice(0,10).join(" "),a={type:"context",itype:(c.cache(a,"params")||{}).type,before:h[0],after:h[2],txt:h[1],loc:location.href,out:c.getActualHref(a),v:2},d.log("info",c.toQuery(a))))},j={};c.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};var C=c.exceptionLogger(function(){var a=!0===window.document.__v5k;window.document.__v5k=!0;a||(this.initLibEvents(),this.initNamespace(),this.initOptions(),c.exceptionLogger(c.bind(this.logException,
this),!f.dev),this.initProcessors(),this.initDRApi(),this.initApi(),this.enabled()&&(this.initLegacyCallbacks(),this.ping()))}),o=[],v,u=1,y={},z=function(){var a=!1,b={},g=function(a){return function(){if(a){var b=c.toArray(arguments);b.unshift("custom",a);d.log.apply(this,b)}}};v=null;c.each(y,function(h,k){h.setup=h.setup||window.vglnk&&window.vglnk[k+"_plugin"];h.setup?(!h.run&&"function"===c.type(h.setup)&&(h.run=h.setup(h.opts,c.clone(c),n,g(h.opts.key))||c.noop),h.opts.mode===d.PLUGIN_MANUAL?
b[k]=h:h.run()):(a=!0,b[k]=h)});y=b;a&&(v=setTimeout(c.exceptionLogger(z),Math.min(Math.max(Math.pow(2,++u),100),5E3)))},A=function(a){return function(){delete y[a].opts.mode;u=1;clearTimeout(v);z()}},B=c.canonicalizeHostname(document.location),w=c.generateNodeFilter({rels:["norewrite","noskim"],custom:function(a){var b,g="";try{b=a.hostname,g=a.protocol,b.charAt(0)}catch(h){return!0}""!==b&&(b=c.canonicalizeHostname(a));return""===b||B===b||!g.match(/^https?:$/i)||f.norewrite[b]||!(f.rewrite_original||
c.cache(a,"type"))}}),s,x=!1,r={},E=!1,D=[],b=function(a){if(void 0===a)return D;"function"===c.type(a)&&(D.push({id:c.uniqid(),fn:a}),E&&this.initLinks())};b(function(){E=!0});d={PLUGIN_MANUAL:1,api:function(a,b,g){a=f.api_url+"/"+a;b=c.extend({cuid:f.cuid,key:f.key,drKey:f.key?null:f.dr_key,loc:location.href,subId:f.sub_id,v:1},b);b.subId&&b.key!==f.key&&(b.subId=null);return c.request(a,b,g)},addEventListener:function(a,b){this.fire(a,b)},click:function(a,b){var g,h,k,d,j=c.context(a)||window;
b=a.target||b;b=!b||b===j.name||"_top"===b&&j.top===j||"_parent"===b&&j.parent===j?"_self":b;"_self"===b?k=j:c.traits.crossWindowCommunication&&c.traits.jsRedirectSetsReferrer?(h=j.open("",b),h.focus(),k=h):k=void 0;if("_self"!==b&&(!c.traits.crossWindowCommunication||!c.traits.jsRedirectSetsReferrer))d="go";else try{if(void 0===k.document)throw!0;d="jsonp"}catch(e){d="go"}g=c.destructing(c.bind(function(){f.time_click&&arguments.length&&this.logTime("clk");var g=c.toArray(arguments);g.unshift(a,
k,b);this.onApiClick.apply(this,g)},this));c.cache(this,"link","string"===typeof a?a:c.getActualHref(a));if("string"===typeof a&&(a=c.createA(a,b),!this.processLink(a))||!f.enabled)return g();h=this.clickParams(a,d);this.logTime();f.log_context&&m(a);if("go"===d)this.redirect(this.api("click",h,{"return":!0}),j,k,b);else if(k===j)this.api("click",h,{fn:g,timeout:f.click_timeout});else{if(c.contextIsAncestor(j,k))return this.redirect(c.getActualHref(a),j,k,b);g=c.exceptionLogger(g);setTimeout(function(){g()},
f.click_timeout);k.document.open();k.callback=g;k.document.write("\x3chtml\x3e\x3chead\x3e\x3ctitle\x3e"+c.getActualHref(a)+'\x3c/title\x3e\x3cscript type\x3d"text/javascript" src\x3d"'+this.api("click",h,{fn:"callback","return":!0})+'"\x3e\x3c/script\x3e\x3c/head\x3e\x3c/html\x3e');k.document.close()}},clickParams:function(a,b){var g=c.extend(c.cache(a,"params"),{format:b,libId:f.library_id,out:c.getActualHref(a),ref:window.document.referrer||null,reaf:f.reaffiliate||null,title:window.document.title,
txt:a.innerHTML});128<g.txt.length&&(g.txt=g.txt.replace(/<[^>]+>/g,""),g.txt=128<g.txt.length?g.txt.substr(0,125)+"...":g.txt);return g},enabled:function(){if(f.enabled&&p!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))f.enabled=!1;return f.enabled},expose:function(a,b){if(b=b||this[a])"function"===typeof b?b=c.exceptionLogger(c.bind(b,this)):"object"===typeof b&&(b=c.clone(b)),n[a]||(n[a]=b)},fire:function(a,b){a=a.toLowerCase();var g=j[a]||{fired:!1,listeners:[]};
"function"===typeof b?g.fired?b({type:a}):g.listeners.push(b):(g.fired=!0,c.each(g.listeners,function(b){"function"===typeof b&&b({type:a})}),g.listeners=[]);j[a]=g},handleRightClick:function(a,b){if(f.rewrite_modified&&a&&b)switch(b){case "setup":c.cache(a,"href")||c.cache(a,"href",a.href);a.href=this.api("click",this.clickParams(a,"go"),{"return":!0});setTimeout(c.exceptionLogger(c.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":a.href=c.cache(a,"href"),c.cache(a,
"href",null)}},harmony:function(a){return f.harmony_level<=a},init:C,initApi:function(){var a,b={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(b[a]=window.vglnk[a]);n=p[e]=c.noop;this.expose("click");this.expose("link",function(a){"element"===c.type(a)&&a.href&&(d.initContext(c.context(a)),d.processLink(a))});this.expose("$",c.clone(c));this.expose("api");this.expose("opt");this.expose("registerProcessor",function(){if(0<arguments.length)return d.registerProcessor.apply(d,arguments)});
c.extend(n,n===window.vglnk?b:{})},initContext:function(a){if(void 0===a)return o;a&&!c.contains(o,a)&&(o.push(a),this.initLinks(a),this.initEvents(a))},initDRApi:function(){var a=!1;window.DrivingRevenue=c.exceptionLogger(c.destructing(c.bind(function(){a=!0;f.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));c.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(b){window.DrivingRevenue=void 0}})},initEvents:function(a){var b={left:d.onClick,right:d.onContextmenu},g={left:c.noop,
right:c.noop},h=c.traits.windowLevelHandlers?a:a.document,k=function(h){h=h||a.event;if((h=c.eventLink(h))&&!c.cache(h,"evented"))j(h,d.harmony(c.harmony.LINK_LEVEL_EVENTS)?b:g),c.cache(h,"evented",!0)},j=function(a,b){c.on(a,"click",c.bind(b.left,d));c.on(a,"contextmenu",c.bind(b.right,d))};c.on(h,"copy",c.bind(d.onCopy,d));c.on(h,"mousedown",k);if(d.harmony(c.harmony.LINK_LEVEL_EVENTS))c.on("DOMReady",function(){c.each(a.document.links,function(a){c.on(a,"mousedown",k)})});(!c.traits.quirksMode||
d.harmony(c.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&j(h,b)},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)void 0!==window[a]&&(n[b[a]]=window[a],"vglnk_domain"===a&&(n[b[a]]+="/api"))},initLegacyCallbacks:function(){var a,b={vl_cB:c.bind(this.onApiClick,this),vl_disable:function(){f.enabled=!1}};for(a in b)window[a]=b[a]},initLibEvents:function(){c.on(d);c.ready(c.bind(function(){this.fire("DOMReady")},
this))},initLinks:function(a){var b=c.bind(function(a){c.each(c.toArray(a.document.links),c.bind(this.processLink,this))},this);void 0===a?c.each(this.initContext(),b):b(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(e="vglnk");var a=window,b=e.split("."),g;for(e=b.pop();0<b.length;)g=b.shift(),a[g]=a[g]||{},a=a[g];p=a;n=p[e]=p[e]||{}},initOptions:function(){var a;this.initLegacyOptions();f=c.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",
cuid:null,dev:!1,dr_key:null,enabled:c.traits.basicCompatibility,key:null,partner:null,sub_id:null,reaffiliate:!1,harmony_level:0,rewrite_original:!0,rewrite_modified:!1}),f,n,{click_timeout:1E3,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},plugins:{link_affiliation:{},modified_clicks:{}},time_click:!1,time_ping:!1,testing_js:[]});for(a in f)"_plugin"===a.substr(-7)&&delete f[a]},initPlugins:function(a){for(var b in a)"object"===typeof a[b]&&!1!==a[b].enabled&&(y[b]=
{opts:a[b]},a[b].mode===this.PLUGIN_MANUAL&&this.expose("init_"+b,A(b)));z()},initProcessors:function(){this.registerProcessor(function(a){var b;b=c.createA(f.api_url);if("/api/click"===a.pathname&&(a.hostname===b.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))b=c.fromQuery(a.search),void 0!==b.out&&(a.href=b.out,delete b.out,c.cache(a,"params",b))});this.registerProcessor(function(a){f.nofollow[a.href]&&!c.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&
(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&c.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},isRewritable:function(a){return w(a,{ancestors:!1})},log:function(a,b,g,h){var k,d=c.toQuery({nocache:c.uniqid()});k="pixel.gif";if("custom"===a)d+="\x26"+c.toQuery({key:b,type:g}),c.each("array"===c.type(h)?h:[h],function(a){c.each(["e","i","o"],function(b){delete a[b]});d+="\x26"+c.toQuery(a)});else{d+="\x26"+c.toQuery({key:f.key,drKey:f.key?
null:f.dr_key});if("time"===a)k="time.gif",a={libId:f.library_id,time:g,type:b};else if("exception"===a)a={e:b,o:g};else if("info"===a)a={i:b};else return;d+="\x26"+c.toQuery(a)}k=f.api_url+"/"+k+"?"+d;c.transmitsPII(k)||(c.createEl("img").src=k)},logException:function(a){if(f.debug){var b={link:c.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?b.message=a:b=c.extend(b,a);this.log("exception",a,c.toQuery(b))}},logTime:function(a){0===arguments.length?s=(new Date).getTime():
this.log("time",a,(new Date).getTime()-s)},onApiClick:function(a,b,g,h,d){var j=h||c.getActualHref(a),e=c.bind(function(){this.redirect(j,c.context(a),b,g)},this);"object"===typeof d&&(d.tracking||d.image)?(h=c.createEl(d.tracking?"iframe":"img",{src:d.tracking||d.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(h),setTimeout(c.exceptionLogger(e),d.timeout||f.hop_timeout)):e()},onApiPing:function(a,b,g,h,k,j){f.rewrite_original=!1;k=c.reformatKeys(k||{});var e,m;h=function(a){var b=
{},g=function(a){c.isArray(a)?b[a[0]]=a[1]:b[a]=1};c.isArray(a)&&c.each(a,g);return b};m=c.extend(f.plugins,k.plugins);f=c.extend(f,k);delete f.plugins;f.library_id=a;f.click_timeout=b;f.time_ping&&this.logTime("png");"array"===c.type(f.testing_js)&&0<f.testing_js.length&&c.each(f.testing_js,function(a){c.jsonp(a)});c.extend(f.norewrite,h(g));c.extend(f.nofollow,h(j));for(e in f)"on"===e.toLowerCase().substr(0,2)&&(2<e.length&&"function"===c.type(f[e]))&&(c.on(d,e.toLowerCase().substr(2),c.bind(f[e],
window)),delete f[e]);this.initPlugins(m);this.initContext(window);this.fire("libready")},onClick:function(a){a=a||window.event;var b=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,g=a.which&&1===a.which||0===a.button,h=c.eventLink(a);if(h&&this.isRewritable(h)&&!b&&g&&!c.isDefaultPrevented(a))return this.click(h),c.preventDefault(a)},onContextmenu:function(a){(a=c.eventLink(a||window.event))&&this.isRewritable(a)&&this.handleRightClick(a,"setup")},onCopy:function(){var a,b,g,h,k=[];if(window.getSelection){g=
window.getSelection();a=0;for(b=g.rangeCount;a<b;a++){try{h=g.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(j){}0<h.length&&128>=h.length&&k.push(h)}}c.each(k,function(a){d.log("info",c.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,b){void 0!==b&&void 0!==this.publicOptions()[a]&&(f[a]=b);return f[a]},ping:function(){if(!x&&(f.key||f.dr_key)){var a={ref:document.referrer||null};x=!0;c.transmitsPII(this.api("ping",a,{"return":!0}))||
(this.logTime(),this.api("ping",a,{fn:c.bind(this.onApiPing,this)}))}},processLink:function(a){if(this.isRewritable(a)){var b=c.cache(a,"processors")||{};c.each(this.registerProcessor(),function(g){b[g.id]||g.fn(a);b[g.id]=!0});c.cache(a,"processors",b);return a}},publicOptions:function(a){"object"===c.type(a)&&(r=a);return c.extend({},r)},redirect:function(a,b,g,h){!c.traits.crossWindowCommunication&&!g?(h=b.open(a,h),h.focus()):c.traits.jsRedirectSetsReferrer?setTimeout(c.exceptionLogger(function(){!g||
g===b?b.location=a:c.contextIsAncestor(b,g)?g.location=a:g.location.replace(a)}),0):("_blank"===h&&(h=c.uniqid("win_")),h=c.createA(a,h),h.rel="norewrite",b.document.body.appendChild(h),h.click(),h.parentNode.removeChild(h))},registerProcessor:b};d.init();try{delete window.vglnk_self}catch(g){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};window.vglnk.link_affiliation_plugin=function(e,d,c){return function(){c.opt("rewrite_original",!0)}};
window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(e,d,c){return function(){c.opt("rewrite_modified",!0)}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(e,d,c){e=d.extend({key:null},e);var l={init:function(){d.each(this.getDRSearchForms(),function(c){if(!d.cache(c,"evented")){var e=l.getInput(c),n=function(){e.value||d.css(e,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};d.cache(c,"evented",!0);c.onsubmit=null;e.onfocus=null;e.onblur=null;d.on(e,"focus",function(){d.css(e,{"background-image":"none"})});d.on(e,"blur",n);n();d.on(c,"submit",function(d){l.onSubmit(d,c)})}})},
getDRSearchForms:function(){var c=[];d.each(document.getElementsByTagName("form"),function(d){l.getInput(d)&&d.id.match(/^DR-ebay-search(CSS|2)?$/i)&&c.push(d)});return c},getInput:function(c){return c.p||c.q2},onSubmit:function(f,p){f=f||window.event;var n="http://shop.ebay.com/i.html?"+d.toQuery({_nkw:l.getInput(p).value}),n=d.createA(n,"_blank");d.cache(n,"params",{key:e.key});c.click(n);return d.preventDefault(f)}};return function(){e.key&&(l.init(),d.on("DOMReady",d.bind(l.init,l)))}};
window.vglnk=window.vglnk||{};
window.vglnk.link_optimization_plugin=function(e,d,c){var l,f,p={};e=d.extend({platform:null},e);d=d.extend(d,{select:window.vglnk.Sizzle||function(){return[]}});l={bbp:{id_finder:["li",/^post-(\d+)$/]},hdlr:{id_finder:["div",/^post_(\d+)$/]},ipb:{id_finder:["div",/^post_id_(\d+)$/]},phpb:{id_finder:["div.post",/^p(\d+)$/]},ubb:{id_finder:["a",/^Post(\d+)$/,"name"]},vb3:{id_finder:["td",/^td_post_(\d+)$/]},vb4:{id_finder:["li",/^post_(\d+)$/]},wppr:{id_finder:["div",/^post-(\d+)$/]}}[e.platform]||
{};var n=function(c){var e=c.textContent||c.innerText;c=d.canonicalizeHostname(c);e=d.createEl("a",{href:e});return d.canonicalizeHostname(e)===c},m=d.generateNodeFilter({classes:["nooptimize"],rels:["nooptimize"],custom:function(c,e){return e?Boolean(d.cache(c,"type")):!1}});f={getLinks:function(j){c.api("optimize",{pt:e.platform,i:j?j.join("|"):null,u:location.href},{fn:d.bind(f.onOptimizeApi,f)})},getPostIDs:function(){var c=[],e=l?l.id_finder:null;e&&d.each(d.select(e[0]),function(d){var f=e[2]||
"id";(d=d[f]?d[f].match(e[1]):null)&&c.push(d[1])});return c.length?c:null},onOptimizeApi:function(j){"object"===d.type(j)&&"object"===d.type(j.optLinks)&&(p=j.optLinks,c.registerProcessor(d.bind(this.optimizeLink,f)))},optimizeLink:function(c){var e=p[c.href];if(e&&m(c)){var f=c.textContent||c.innerText,l;if(!(l=c.href===f))n(c)?(l=d.fromQuery(c.search),l=d.find(l,function(c){return c===f})):l=!1;if(l){l=e.optLink;for(var u;u=c.firstChild;)c.removeChild(u);c.appendChild(document.createTextNode(l))}else if(n(c))return;
d.cache(c,"params",{type:"LO",origOutId:e.pcid+":"+e.linkId});c.href=e.optLink}},setup:function(){var c=d.bind(function(){this.getLinks(this.getPostIDs())},this);if(!e.platform||"full"===e.platform)c();else d.on("DOMReady",c)}};f.setup()};window.vglnk=window.vglnk||{};window.vglnk.page_harmony_plugin=function(e,d,c){e=d.extend({level:null},e);return function(){var d=parseInt(e.level,10);isFinite(d)&&c.opt("harmony_level",d)}};window.vglnk=window.vglnk||{};
window.vglnk.partner_integration_plugin=function(e,d,c){e=d.extend({eb_campaign:5337208431,eb_cid:null,eb_gid:null,eb_group:null,eb_pct:0,eb_rotation:"711-53200-19255-0"},e);var l=/(^|\.)ebay\.com$/,f=/(^|\.)rover\.ebay\.com$/,p={injectPixel:function(){if(e.eb_cid&&e.eb_campaign&&e.eb_rotation&&"number"===d.type(e.eb_gid)&&isFinite(e.eb_gid)&&0<=e.eb_gid){var c,f="//rover.ebay.com/roverimp/1/"+encodeURIComponent(e.eb_rotation)+"/1",j={campid:e.eb_campaign,ff19:e.eb_cid,ff20:e.eb_gid,mpt:Math.floor(99999999*
Math.random()),pub:5574713606,toolid:2E4};c=d.createEl("img",{src:f+"?"+d.toQuery(j)},{border:"none",height:0,width:0,position:"absolute",zIndex:-1});d.on("DOMReady",function(){document.body&&document.body.appendChild(c)})}},expandTruncatedUrl:function(c,d){var e;e=d.textContent||d.innerText;if(e&&(-1!==e.indexOf("...")||-1!==e.indexOf("\u2026"))){var f=e.split("...")[0].split("\u2026")[0],o=c.replace(/^http:\/\//i,"");e=f.length<c.length&&c.substr(0,f.length)===f||f.length<o.length&&o.substr(0,f.length)===
f&&-1!==e.indexOf("/")}else e=void 0;if(e){for(;e=d.firstChild;)d.removeChild(e);d.appendChild(document.createTextNode(c))}},shouldBeUnlinked:function(c,e){var j=d.canonicalizeHostname(c);return l.test(j)&&("inserted"===d.cache(e,"type")||!f.test(j))},unlink:function(c){var e,j,f=!0,o=d.getActualHref(c);if(this.shouldBeUnlinked(o,c)){e=document.createDocumentFragment();if(c.parentNode){for(;j=c.firstChild;)f=f&&3===j.nodeType,e.appendChild(j);f&&this.expandTruncatedUrl(o,e);c.parentNode.insertBefore(e,
c);c.parentNode.removeChild(c)}d.cache(c,"unlinked",!0)}}};null===e.eb_group&&(e.eb_group=e.eb_gid/10<e.eb_pct?1:0);return function(){p.injectPixel();1===e.eb_group&&c.registerProcessor(d.bind(p.unlink,p))}};window.vglnk=window.vglnk||{};
window.vglnk.product_linker_plugin=function(e,d,c,l){var f,p,n=null,m={},j,C=0,o=0,v=0,u=0;e=d.extend({cat:null,platform:null,key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,product_source:null,proximity:null,same_proximity:100,scope:null,type:null,ui:!0},e);if(e.key){d=d.extend(d,{matches:window.vglnk.Sizzle.matchesSelector||function(){return!0},select:window.vglnk.Sizzle||function(){return[]}});f={bbp:{id_finder:["li",/^post-(\d+)$/],scope:"li .post"},hdlr:{id_finder:["div",
/^post_(\d+)$/],scope:".post-content-area"},ipb:{id_finder:["div",/^post_id_(\d+)$/],scope:".post_body .post"},phpb:{id_finder:["div.post",/^p(\d+)$/],scope:".postbody .content, .postbody .signature"},ubb:{id_finder:["a",/^Post(\d+)$/,"name"],scope:".post_inner *[id^\x3d'body'], .post_inner .signature"},vb3:{id_finder:["div[id], table[id]",/^post(\d+)$/],scope:"td[id^\x3d'td_post_'] div[id^\x3d'post_message_'],td[id^\x3d'td_post_'] div[id^\x3d'post_message_'] ~ div:not([class])"},vb4:{id_finder:["li",
/^post_(\d+)$/],scope:".postbody .content, .postbody .signature, .post-content, ul.conversation-list .list-item-body"},wppr:{id_finder:["div",/^post-(\d+)$/],scope:null}}[e.platform]||{};var y={timing:!1,data:e.link_phrases?!1:e.link_urls},z=function(c){var f=!1,x=c.parentNode;c.data&&(f=j.test(c.data.replace(/\s+/," ")));if(f)for(var r=c,l,n,b,f=function(a,b){var g,c,i,h,k,t,f,j,w,s,r=function(b){w.parentNode.insertBefore(a,w);w.parentNode.removeChild(w);return b};w=d.createEl("span");a.parentNode.insertBefore(w,
a);w.appendChild(a);s=d.geometry(w);if(e.proximity||e.same_proximity)for(t in m)if((f=m[t].links)&&!(m[t]===b&&!e.same_proximity||m[t]!==b&&!e.proximity)){j=m[t]===b?Math.max(e.same_proximity,e.proximity):e.proximity;g=0;for(c=f.length;g<c;g++){k=f[g].segments;i=0;for(h=k.length;i<h;i++){var l=k[i].geometry,n=s,x=j,l=d.extend({},l);l.x1-=x;l.y1-=x;l.x2+=x;l.y2+=x;if(l.x1<n.x2&&l.x2>n.x1&&l.y1<n.y2&&l.y2>n.y1)return r(!1)}}}return r(!0)};r&&r.data&&(Boolean(n=r.data.match(/^\s+/))||Boolean(n=r.data.match(j)));){l=
n[0];b=n.slice(1).join("");c=m[b.toLowerCase()];l=r.data.indexOf(l)+l.length-b.length;0<l&&(r=r.splitText(l));l=r.length<=b.length?null:r.splitText(b.length);b&&!c&&(c={url:b.match(/^https?:\/\//i)?b:"http://"+b,type:"U"});var g;if(g=b){var a=g=void 0;g=!c||!e.per_phrase||!c.count||c.count<e.per_phrase;a=!e.per_page||C<e.per_page;g=g&&a&&f(r,c)}if(g&&(g=c,a=void 0,a=d.createEl("a"),a.innerHTML=b.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"\x3cspan\x3e$1\x3c/span\x3e"),a.className="vglnk",d.cache(a,"type",
"inserted"),d.cache(a,"phrase",b),e.ui&&(a.title="Link added by VigLink"),p.initLink(a,g),b=a,!d.cache(b,"unlinked"))){"U"===c.type?u++:"L"===c.type.toUpperCase()?o++:v++;x.insertBefore(b,r);x.removeChild(r);var r=c,i=a=g=void 0,t=void 0,h={el:b,segments:[]};b=b.getElementsByTagName("span");var k={els:[]};g=0;for(a=b.length;g<a;g++)i=b[g],void 0===t||i.offsetTop===t.offsetTop?k.els.push(i):(h.segments.push(k),k={els:[i]}),t=i;k.geometry=d.geometry.apply(d,k.els);h.segments.push(k);r.links=r.links||
[];r.links.push(h);c.count++;C++}r=l}},A=d.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(c){return d.matches(c,"a[href]")}}),B=function(c){var f;if(c){if(A(c,{ancestors:!1,self:!0}))for(f=c.firstChild;f;)c=f.nextSibling,1===f.nodeType?B(f):3===f.nodeType&&z(f),f=c}else d.each(d.select(e.scope),function(c){A(c,{ancestors:!0,self:!1})&&
B(c)})};p={addPhrasesToMatcher:function(c){var e="";"regexp"===d.type(c)?e=c.source:"array"===d.type(c)&&(e="(?:^|[\\s\"'\\(])("+d.map(c,d.escapeRegExp).join("|")+")(?\x3d\\s|\\W*$|\\W{2})");""!==e&&(j=RegExp(j?"(?:"+e+"|"+j.source+")":e,"i"))},focusLink:function(c){c.id||(c.id=d.uniqid("vl-link-"));location.href.hash="#"+c.id;window.scrollBy(0,-150)},getPhrases:function(f){c.api("insert",d.extend(p.getPartnerParams(),{cat:e.cat,mode:e.mode,pt:e.platform,ps:e.product_source,i:f?f.join("|"):null,u:location.href,
type:e.type}),{fn:d.bind(p.onInsertApi,p)})},getPartnerParams:function(){var d,e,f=c.opt("partner"),j={};for(d in f)break;if(d)for(e in f[d])j[d+"_"+e]=f[d][e];return j},getPostIDs:function(){var c=[],e=f?f.id_finder:null;e&&d.each(d.select(e[0]),function(d){var f=e[2]||"id";(d=d[f]?d[f].match(e[1]):null)&&c.push(d[1])});return c.length?c:null},initLink:function(f,j,m){if(m=e.link_target||m)f.target=m;f.rel="nofollow";f.href||(f.href=j.url);d.cache(f,"params",{exp:n,key:e.key,mid:j.mid,type:j.type||
null});d.cache(f,"href",f.href);c.link(f)},insertLinks:function(c){y=d.extend(y,c);y.timing&&(y.data&&j)&&(B(),p.log())},loadPhrases:function(c){var d,e,f,j=[];d=0;for(e=c.length;d<e;d++)f=c[d],f.phrase&&f.url&&(f.phrase=f.phrase.toLowerCase(),m[f.phrase]||(j.push(f.phrase),m[f.phrase]={count:m[f.phrase]?m[f.phrase].count:0,phrase:f.phrase,mid:f.mid,url:f.url,type:f.type||""}));0<j.length&&this.addPhrasesToMatcher(j);this.insertLinks({data:!0})},log:function(){var c,d,f={heavy:[],lite:[]},e=function(c,
d){return d.split(",")[0]-c.split(",")[0]};for(c in m)d=parseInt(m[c].count,10),0<d&&(d=[d,c.replace(/\|/g,"%7C")].join(),f["L"===m[c].type.toUpperCase()?"lite":"heavy"].push(d));f.lite.sort(e);f.heavy.sort(e);l("insert",[{ct:C,cl:o,ch:v,cu:u,exp:n},{pl:f.lite.join("|")},{ph:f.heavy.join("|")}])},onInsertApi:function(c){"object"===d.type(c)&&(n=c.exp,c.results&&this.loadPhrases(c.results))},setup:function(){var c=d.bind(function(){this.getPhrases(this.getPostIDs())},this);e.scope=e.scope||f.scope||
"body";e.link_urls&&this.addPhrasesToMatcher(RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()\x3c\x3e]+|\\((?:[^\\s()\x3c\x3e]|(?:\\([^\\s()\x3c\x3e]+\\)))*\\))+(?:\\((?:[^\\s()\x3c\x3e]|(?:\\([^\\s()\x3c\x3e]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,\x3c\x3e?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))","i"));if(e.link_phrases)if(!e.platform||"full"===e.platform)c();else d.on("DOMReady",c)}};p.setup();return function(){d.on("DOMReady",
function(){p.insertLinks({timing:!0})})}}};window.vglnk=window.vglnk||{};window.vglnk.product_widget_plugin=function(e,d,c){window.vglnk.product_widget_plugin.exports={$:d,opts:e,vglnk:c};return function(){(!d.browser.ie||6<d.browser.version)&&d.jsonp(c.opt("asset_url")+"/products.js")}};
(function(){function e(b,g,a,c,d,h){d=0;for(var f=c.length;d<f;d++){var e=c[d];if(e){for(var j=!1,e=e[b];e;){if(e.sizcache===a){j=c[e.sizset];break}1===e.nodeType&&!h&&(e.sizcache=a,e.sizset=d);if(e.nodeName.toLowerCase()===g){j=e;break}e=e[b]}c[d]=j}}}function d(b,c,a,i,d,h){d=0;for(var e=i.length;d<e;d++){var f=i[d];if(f){for(var j=!1,f=f[b];f;){if(f.sizcache===a){j=i[f.sizset];break}if(1===f.nodeType)if(h||(f.sizcache=a,f.sizset=d),"string"!==typeof c){if(f===c){j=!0;break}}else if(0<m.filter(c,
[f]).length){j=f;break}f=f[b]}i[d]=j}}}var c=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,l=0,f=Object.prototype.toString,p=!1,n=!0;[0,0].sort(function(){n=!1;return 0});var m=function(b,g,a,i){a=a||[];var d=g=g||document;if(1!==g.nodeType&&9!==g.nodeType)return[];if(!b||"string"!==typeof b)return a;var h,e,l,n,o,p=!0,r=m.isXML(g),q=[],s=b;do if(c.exec(""),h=c.exec(s))if(s=h[3],q.push(h[1]),h[2]){n=h[3];break}while(h);
if(1<q.length&&C.exec(b))if(2===q.length&&j.relative[q[0]])e=D(q[0]+q[1],g);else for(e=j.relative[q[0]]?[g]:m(q.shift(),g);q.length;)b=q.shift(),j.relative[b]&&(b+=q.shift()),e=D(b,e);else if(!i&&(1<q.length&&9===g.nodeType&&!r&&j.match.ID.test(q[0])&&!j.match.ID.test(q[q.length-1]))&&(h=m.find(q.shift(),g,r),g=h.expr?m.filter(h.expr,h.set)[0]:h.set[0]),g){h=i?{expr:q.pop(),set:u(i)}:m.find(q.pop(),1===q.length&&("~"===q[0]||"+"===q[0])&&g.parentNode?g.parentNode:g,r);e=h.expr?m.filter(h.expr,h.set):
h.set;for(0<q.length?l=u(e):p=!1;q.length;)h=o=q.pop(),j.relative[o]?h=q.pop():o="",null==h&&(h=g),j.relative[o](l,h,r)}else l=[];l||(l=e);l||m.error(o||b);if("[object Array]"===f.call(l))if(p)if(g&&1===g.nodeType)for(b=0;null!=l[b];b++)l[b]&&(!0===l[b]||1===l[b].nodeType&&m.contains(g,l[b]))&&a.push(e[b]);else for(b=0;null!=l[b];b++)l[b]&&1===l[b].nodeType&&a.push(e[b]);else a.push.apply(a,l);else u(l,a);n&&(m(n,d,a,i),m.uniqueSort(a));return a};m.uniqueSort=function(b){if(z&&(p=n,b.sort(z),p))for(var c=
1;c<b.length;c++)b[c]===b[c-1]&&b.splice(c--,1);return b};m.matches=function(b,c){return m(b,null,null,c)};m.matchesSelector=function(b,c){return 0<m(c,null,null,[b]).length};m.find=function(b,c,a){var i;if(!b)return[];for(var d=0,h=j.order.length;d<h;d++){var e,f=j.order[d];if(e=j.leftMatch[f].exec(b)){var l=e[1];e.splice(1,1);if("\\"!==l.substr(l.length-1)&&(e[1]=(e[1]||"").replace(/\\/g,""),i=j.find[f](e,c,a),null!=i)){b=b.replace(j.match[f],"");break}}}i||(i="undefined"!==typeof c.getElementsByTagName?
c.getElementsByTagName("*"):[]);return{set:i,expr:b}};m.filter=function(b,c,a,i){for(var d,h,e=b,f=[],l=c,n=c&&c[0]&&m.isXML(c[0]);b&&c.length;){for(var o in j.filter)if(null!=(d=j.leftMatch[o].exec(b))&&d[2]){var p,q,r=j.filter[o];q=d[1];h=!1;d.splice(1,1);if("\\"!==q.substr(q.length-1)){l===f&&(f=[]);if(j.preFilter[o])if(d=j.preFilter[o](d,l,a,f,i,n)){if(!0===d)continue}else h=p=!0;if(d)for(var s=0;null!=(q=l[s]);s++)if(q){p=r(q,d,s,l);var u=i^!!p;a&&null!=p?u?h=!0:l[s]=!1:u&&(f.push(q),h=!0)}if(void 0!==
p){a||(l=f);b=b.replace(j.match[o],"");if(!h)return[];break}}}if(b===e)if(null==h)m.error(b);else break;e=b}return l};m.error=function(b){throw"Syntax error, unrecognized expression: "+b;};var j=m.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(?:(['"])(.*?)\3|(#?(?:[\w\u00c0-\uFFFF\-]|\\.)*)|)|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,
CHILD:/:(only|nth|last|first)-child(?:\(\s*(even|odd|(?:[+\-]?\d+|(?:[+\-]?\d*)?n\s*(?:[+\-]\s*\d+)?))\s*\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(b){return b.getAttribute("href")}},relative:{"+":function(b,c){var a="string"===typeof c,d=a&&!/\W/.test(c),a=a&&!d;d&&(c=c.toLowerCase());for(var d=0,e=
b.length,h;d<e;d++)if(h=b[d]){for(;(h=h.previousSibling)&&1!==h.nodeType;);b[d]=a||h&&h.nodeName.toLowerCase()===c?h||!1:h===c}a&&m.filter(c,b,!0)},"\x3e":function(b,c){var a,d="string"===typeof c,e=0,h=b.length;if(d&&!/\W/.test(c))for(c=c.toLowerCase();e<h;e++){if(a=b[e])a=a.parentNode,b[e]=a.nodeName.toLowerCase()===c?a:!1}else{for(;e<h;e++)(a=b[e])&&(b[e]=d?a.parentNode:a.parentNode===c);d&&m.filter(c,b,!0)}},"":function(b,c,a){var i,f=l++,h=d;"string"===typeof c&&!/\W/.test(c)&&(i=c=c.toLowerCase(),
h=e);h("parentNode",c,f,b,i,a)},"~":function(b,c,a){var i,f=l++,h=d;"string"===typeof c&&!/\W/.test(c)&&(i=c=c.toLowerCase(),h=e);h("previousSibling",c,f,b,i,a)}},find:{ID:function(b,c,a){if("undefined"!==typeof c.getElementById&&!a)return(b=c.getElementById(b[1]))&&b.parentNode?[b]:[]},NAME:function(b,c){if("undefined"!==typeof c.getElementsByName){for(var a=[],d=c.getElementsByName(b[1]),e=0,h=d.length;e<h;e++)d[e].getAttribute("name")===b[1]&&a.push(d[e]);return 0===a.length?null:a}},TAG:function(b,
c){if("undefined"!==typeof c.getElementsByTagName)return c.getElementsByTagName(b[1])}},preFilter:{CLASS:function(b,c,a,d,e,h){b=" "+b[1].replace(/\\/g,"")+" ";if(h)return b;h=0;for(var f;null!=(f=c[h]);h++)f&&(e^(f.className&&0<=(" "+f.className+" ").replace(/[\t\n\r]/g," ").indexOf(b))?a||d.push(f):a&&(c[h]=!1));return!1},ID:function(b){return b[1].replace(/\\/g,"")},TAG:function(b){return b[1].toLowerCase()},CHILD:function(b){if("nth"===b[1]){b[2]||m.error(b[0]);b[2]=b[2].replace(/^\+|\s*/g,"");
var c=/(-?)(\d*)(?:n([+\-]?\d*))?/.exec("even"===b[2]&&"2n"||"odd"===b[2]&&"2n+1"||!/\D/.test(b[2])&&"0n+"+b[2]||b[2]);b[2]=c[1]+(c[2]||1)-0;b[3]=c[3]-0}else b[2]&&m.error(b[0]);b[0]=l++;return b},ATTR:function(b,c,a,d,e,h){c=b[1]=b[1].replace(/\\/g,"");!h&&j.attrMap[c]&&(b[1]=j.attrMap[c]);b[4]=(b[4]||b[5]||"").replace(/\\/g,"");"~\x3d"===b[2]&&(b[4]=" "+b[4]+" ");return b},PSEUDO:function(b,g,a,d,e){if("not"===b[1])if(1<(c.exec(b[3])||"").length||/^\w/.test(b[3]))b[3]=m(b[3],null,null,g);else return b=
m.filter(b[3],g,a,1^e),a||d.push.apply(d,b),!1;else if(j.match.POS.test(b[0])||j.match.CHILD.test(b[0]))return!0;return b},POS:function(b){b.unshift(!0);return b}},filters:{enabled:function(b){return!1===b.disabled&&"hidden"!==b.type},disabled:function(b){return!0===b.disabled},checked:function(b){return!0===b.checked},selected:function(b){return!0===b.selected},parent:function(b){return!!b.firstChild},empty:function(b){return!b.firstChild},has:function(b,c,a){return!!m(a[3],b).length},header:function(b){return/h\d/i.test(b.nodeName)},
text:function(b){return"text"===b.type},radio:function(b){return"radio"===b.type},checkbox:function(b){return"checkbox"===b.type},file:function(b){return"file"===b.type},password:function(b){return"password"===b.type},submit:function(b){return"submit"===b.type},image:function(b){return"image"===b.type},reset:function(b){return"reset"===b.type},button:function(b){return"button"===b.type||"button"===b.nodeName.toLowerCase()},input:function(b){return/input|select|textarea|button/i.test(b.nodeName)}},
setFilters:{first:function(b,c){return 0===c},last:function(b,c,a,d){return c===d.length-1},even:function(b,c){return 0===c%2},odd:function(b,c){return 1===c%2},lt:function(b,c,a){return c<a[3]-0},gt:function(b,c,a){return c>a[3]-0},nth:function(b,c,a){return a[3]-0===c},eq:function(b,c,a){return a[3]-0===c}},filter:{PSEUDO:function(b,c,a,d){var e=c[1],h=j.filters[e];if(h)return h(b,a,c,d);if("contains"===e)return 0<=(b.textContent||b.innerText||m.getText([b])||"").indexOf(c[3]);if("not"===e){c=c[3];
a=0;for(d=c.length;a<d;a++)if(c[a]===b)return!1;return!0}m.error(e)},CHILD:function(b,c){var a=c[1],d=b;switch(a){case "only":case "first":for(;d=d.previousSibling;)if(1===d.nodeType)return!1;if("first"===a)return!0;d=b;case "last":for(;d=d.nextSibling;)if(1===d.nodeType)return!1;return!0;case "nth":var a=c[2],e=c[3];if(1===a&&0===e)return!0;var h=c[0],f=b.parentNode;if(f&&(f.sizcache!==h||!b.nodeIndex)){for(var j=0,d=f.firstChild;d;d=d.nextSibling)1===d.nodeType&&(d.nodeIndex=++j);f.sizcache=h}d=
b.nodeIndex-e;return 0===a?0===d:0===d%a&&0<=d/a}},ID:function(b,c){return 1===b.nodeType&&b.getAttribute("id")===c},TAG:function(b,c){return"*"===c&&1===b.nodeType||b.nodeName.toLowerCase()===c},CLASS:function(b,c){return-1<(" "+(b.className||b.getAttribute("class"))+" ").indexOf(c)},ATTR:function(b,c){var a=c[1],a=j.attrHandle[a]?j.attrHandle[a](b):null!=b[a]?b[a]:b.getAttribute(a),d=a+"",e=c[2],h=c[4];return null==a?"!\x3d"===e:"\x3d"===e?d===h:"*\x3d"===e?0<=d.indexOf(h):"~\x3d"===e?0<=(" "+d+
" ").indexOf(h):!h?d&&!1!==a:"!\x3d"===e?d!==h:"^\x3d"===e?0===d.indexOf(h):"$\x3d"===e?d.substr(d.length-h.length)===h:"|\x3d"===e?d===h||d.substr(0,h.length+1)===h+"-":!1},POS:function(b,c,a,d){var e=j.setFilters[c[2]];if(e)return e(b,a,c,d)}}},C=j.match.POS,o=function(b,c){return"\\"+(c-0+1)},v;for(v in j.match)j.match[v]=RegExp(j.match[v].source+/(?![^\[]*\])(?![^\(]*\))/.source),j.leftMatch[v]=RegExp(/(^(?:.|\r|\n)*?)/.source+j.match[v].source.replace(/\\(\d+)/g,o));var u=function(b,c){b=Array.prototype.slice.call(b,
0);return c?(c.push.apply(c,b),c):b};try{Array.prototype.slice.call(document.documentElement.childNodes,0)}catch(y){u=function(b,c){var a=0,d=c||[];if("[object Array]"===f.call(b))Array.prototype.push.apply(d,b);else if("number"===typeof b.length)for(var e=b.length;a<e;a++)d.push(b[a]);else for(;b[a];a++)d.push(b[a]);return d}}var z,A;document.documentElement.compareDocumentPosition?z=function(b,c){return b===c?(p=!0,0):!b.compareDocumentPosition||!c.compareDocumentPosition?b.compareDocumentPosition?
-1:1:b.compareDocumentPosition(c)&4?-1:1}:(z=function(b,c){var a,d,e=[],h=[];a=b.parentNode;d=c.parentNode;var f=a;if(b===c)return p=!0,0;if(a===d)return A(b,c);if(a){if(!d)return 1}else return-1;for(;f;)e.unshift(f),f=f.parentNode;for(f=d;f;)h.unshift(f),f=f.parentNode;a=e.length;d=h.length;for(f=0;f<a&&f<d;f++)if(e[f]!==h[f])return A(e[f],h[f]);return f===a?A(b,h[f],-1):A(e[f],c,1)},A=function(b,c,a){if(b===c)return a;for(b=b.nextSibling;b;){if(b===c)return-1;b=b.nextSibling}return 1});m.getText=
function(b){for(var c="",a,d=0;b[d];d++)a=b[d],3===a.nodeType||4===a.nodeType?c+=a.nodeValue:8!==a.nodeType&&(c+=m.getText(a.childNodes));return c};o=document.createElement("div");v="script"+(new Date).getTime();var B=document.documentElement;o.innerHTML="\x3ca name\x3d'"+v+"'/\x3e";B.insertBefore(o,B.firstChild);document.getElementById(v)&&(j.find.ID=function(b,c,a){if("undefined"!==typeof c.getElementById&&!a)return(c=c.getElementById(b[1]))?c.id===b[1]||"undefined"!==typeof c.getAttributeNode&&
c.getAttributeNode("id").nodeValue===b[1]?[c]:void 0:[]},j.filter.ID=function(b,c){var a="undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id");return 1===b.nodeType&&a&&a.nodeValue===c});B.removeChild(o);B=o=null;o=document.createElement("div");o.appendChild(document.createComment(""));0<o.getElementsByTagName("*").length&&(j.find.TAG=function(b,c){var a=c.getElementsByTagName(b[1]);if("*"===b[1]){for(var d=[],e=0;a[e];e++)1===a[e].nodeType&&d.push(a[e]);a=d}return a});o.innerHTML="\x3ca href\x3d'#'\x3e\x3c/a\x3e";
o.firstChild&&("undefined"!==typeof o.firstChild.getAttribute&&"#"!==o.firstChild.getAttribute("href"))&&(j.attrHandle.href=function(b){return b.getAttribute("href",2)});o=null;if(document.querySelectorAll){var w=m,o=document.createElement("div");o.innerHTML="\x3cp class\x3d'TEST'\x3e\x3c/p\x3e";if(!(o.querySelectorAll&&0===o.querySelectorAll(".TEST").length)){var m=function(b,c,a,d){c=c||document;if(!d&&!m.isXML(c)){var e=/^(\w+$)|^\.([\w\-]+$)|^#([\w\-]+$)/.exec(b);if(e&&(1===c.nodeType||9===c.nodeType)){if(e[1])return u(c.getElementsByTagName(b),
a);if(e[2]&&j.find.CLASS&&c.getElementsByClassName)return u(c.getElementsByClassName(e[2]),a)}if(9===c.nodeType){if("body"===b&&c.body)return u([c.body],a);if(e&&e[3]){var f=c.getElementById(e[3]);if(f&&f.parentNode){if(f.id===e[3])return u([f],a)}else return u([],a)}try{return u(c.querySelectorAll(b),a)}catch(k){}}else if(1===c.nodeType&&"object"!==c.nodeName.toLowerCase()){var f=(e=c.getAttribute("id"))||"__sizzle__",l=c.parentNode,n=/^\s*[+~]/.test(b);e?f=f.replace(/'/g,"\\$\x26"):c.setAttribute("id",
f);n&&l&&(c=c.parentNode);try{if(!n||l)return u(c.querySelectorAll("[id\x3d'"+f+"'] "+b),a)}catch(o){}finally{e||c.removeAttribute("id")}}}return w(b,c,a,d)},s;for(s in w)m[s]=w[s];o=null}}s=document.documentElement;var x=s.matchesSelector||s.mozMatchesSelector||s.webkitMatchesSelector||s.msMatchesSelector,r=!1;try{x.call(document.documentElement,"[test!\x3d'']:sizzle")}catch(E){r=!0}x&&(m.matchesSelector=function(b,c){c=c.replace(/\=\s*([^'"\]]*)\s*\]/g,"\x3d'$1']");if(!m.isXML(b))try{if(r||!j.match.PSEUDO.test(c)&&
!/!=/.test(c))return x.call(b,c)}catch(a){}return 0<m(c,null,null,[b]).length});s=document.createElement("div");s.innerHTML="\x3cdiv class\x3d'test e'\x3e\x3c/div\x3e\x3cdiv class\x3d'test'\x3e\x3c/div\x3e";s.getElementsByClassName&&0!==s.getElementsByClassName("e").length&&(s.lastChild.className="e",1!==s.getElementsByClassName("e").length&&(j.order.splice(1,0,"CLASS"),j.find.CLASS=function(b,c,a){if("undefined"!==typeof c.getElementsByClassName&&!a)return c.getElementsByClassName(b[1])},s=null));
m.contains=document.documentElement.contains?function(b,c){return b!==c&&(b.contains?b.contains(c):!0)}:document.documentElement.compareDocumentPosition?function(b,c){return!!(b.compareDocumentPosition(c)&16)}:function(){return!1};m.isXML=function(b){return(b=(b?b.ownerDocument||b:0).documentElement)?"HTML"!==b.nodeName:!1};var D=function(b,c){for(var a,d=[],e="",f=c.nodeType?[c]:c;a=j.match.PSEUDO.exec(b);)e+=a[0],b=b.replace(j.match.PSEUDO,"");b=j.relative[b]?b+"*":b;a=0;for(var k=f.length;a<k;a++)m(b,
f[a],d);return m.filter(e,d)};window.vglnk.Sizzle=m})();