/*

  Includes:

  Sizzle CSS Selector Engine
  Copyright 2011, The Dojo Foundation
  Released under the MIT, BSD, and GPL Licenses.
  More information: http://sizzlejs.com/
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Copyright (c) 2013 VigLink. Rights reserved and patent(s) pending.
*/
(function(d){var l,c,i=function(a,j){try{return("function"===typeof window[j]||"object"===typeof window[j])&&a instanceof window[j]}catch(b){}return!1};c={_breaker:{},each:function(a,j){var b,f;if("object"===c.type(a)&&a.hasOwnProperty)for(b in a){if(a.hasOwnProperty(b)&&j(a[b],b)===c._breaker)break}else{b=0;for(f=a.length;b<f&&j(a[b],b)!==c._breaker;b++);}},extend:function(a){var j,b,f,c,g=arguments.length;a=a||{};for(b=1;b<g;b++)if(c=arguments[b],void 0!==c&&null!==c)for(f in c)j=c[f],a!==j&&void 0!==
j&&(a[f]=j);return a},noop:function(){},type:function(a){return null===a?"null":void 0===a?"undefined":i(a,"HTMLElement")||"object"===typeof a&&1===a.nodeType&&"string"===typeof a.nodeName?"element":i(a,"HTMLDocument")||"object"===typeof a&&("defaultView"in a||"parentWindow"in a)?"document":a==a.window?"window":Object.prototype.toString.call(a).slice(8,-1).toLowerCase()}};c.extend(c,{addClass:function(a,j){c.hasClass(a,j)||(a.className=(a.className?a.className+" ":"")+j)},attrValues:function(a,j,
b){return(j=a[j])?j.split(b||" "):[]},bind:function(a,j){return function(){return a.apply(j,arguments)}},browser:function(){var a={},j,b=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);c.each(b,function(b){j=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];a[j?b.substr(0,b.length-j.length-1).replace(/\d*$/,""):b]=j||!0});return{aol:a.aol,blackberry:a.blackberry,ie:a.msie,ios:a.mobile&&a.safari,opera:a.opera,playstation:a.playstation,
version:parseFloat(a.version||a.crios)||!1}}(),cache:function(){var a={},j="vglnk_"+(new Date).getTime(),b=0;return function(c,g,n){if(c){var v=c[j];if(v||void 0!==n)return v||(v=++b),a[v]||(c[j]=v,a[v]={}),void 0!==n&&(a[v][g]=n),"string"===typeof g?a[v][g]:a[v]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=c.createA(a));return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""},clone:function(a){return c.extend({},a)},contains:function(a,j){return-1!==
c.indexOf(a,j)},context:function(a){"element"===c.type(a)&&(a=a.ownerDocument);"document"===c.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===c.type(a))return a},containsPII:function(a){return/\b[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}\b/i.test(a)},contextIsAncestor:function(a,j){for(var b=a.self;b.parent&&b.parent!==b;)if(b=b.parent,b===j)return!0;return!1},cors:function(a){var j,b=function(){eval(j.responseText)};j=new window.XMLHttpRequest;j.onreadystatechange=function(){4===
j.readyState&&200===j.status&&b()};try{j.open("GET",a),j.withCredentials=!0,j.send()}catch(c){return!1}},createA:function(a,j){return c.createEl("a",{href:a,target:j})},createEl:function(a,j,b,f){var g;a=(f||document).createElement(a);j=j||{};b=b||{};for(g in j)void 0!==j[g]&&(a[g]=j[g]);c.css(a,b);return a},css:function(a,j){for(var b in j)try{a.style[b]=j[b]}catch(c){}return a},destructing:function(a){var j=!1,b;return function(){j||(b=a.apply(null,arguments),j=!0);return b}},escapeRegExp:function(){var a;
return function(j){a=a||RegExp("([.*+?^${}()|[\\]\\\\])","g");return j.replace(a,"\\$1")}}(),eventLink:function(a){var j,b=a.target||a.srcElement;do{try{j=b.nodeType}catch(c){break}if(1===j&&(a=b.tagName.toUpperCase(),"A"===a||"AREA"===a))return b;b=b.parentNode}while(b)},exceptionLogger:function(){var a=!1,j=c.noop;return function(b,c){if(void 0!==c)a=c,j=b;else return function(){if(a)try{return b.apply(this,arguments)}catch(c){j(c)}else return b.apply(this,arguments)}}}(),find:function(a,j){var b;
c.each(a,function(a,g){if(j(a,g))return b=a,c._breaker});return b},generateNodeFilter:function(){var a=function(a,j){var b,c;j=","+j.join(",")+",";b=0;for(c=a.length;b<c;b++)if(-1!==j.indexOf(","+a[b]+","))return!0;return!1},j=function(a,j){var b=a.nodeName.toLowerCase();return-1!==j.indexOf(","+b+",")};return function(b){b=c.extend({custom:null,classes:[],rels:[],tags:[]},b);b.tags.length&&(b.tags=","+b.tags.join(",").toLowerCase()+",");return function(g,h){h=c.extend({ancestors:!0,self:!0},h);var n=
!0,v=!0,d=function(g,f){var h;if(h=!(b.tags.length&&j(g,b.tags))){if(h=b.classes.length){h=b.classes;var n=c.attrValues(g,"className");h=a(h,n)}if(h=!h){if(h=b.rels.length)h=b.rels,n=c.attrValues(g,"rel"),h=j(g,",a,")&&a(h,n);h=!h&&!("function"===c.type(b.custom)&&b.custom(g,f))}}return h},v=!h.self||d(g,!0);if(h.ancestors)for(;g.parentNode;)if(g=g.parentNode,1===g.nodeType&&!d(g,!1)){n=!1;break}return v&&n}}}(),fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("\x26");var j={};
c.each(a,function(a){a=a.split("\x3d");j[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return j},geometry:function(){var a,j=arguments.length,b=Infinity,g=Infinity,h=-Infinity,n=-Infinity,d;for(a=0;a<j;a++)d=c.position(arguments[a]),b=Math.min(b,d.x),g=Math.min(g,d.y),h=Math.max(h,d.x+arguments[a].offsetWidth),n=Math.max(n,d.y+arguments[a].offsetHeight);return{x:b,y:g,w:h-b,h:n-g,x1:b,y1:g,x2:h,y2:n}},getActualHref:function(a){return c.cache(a,"href")||a.href},hasAttrValue:function(a,b,g,f){return b?
c.contains(c.attrValues(a,b,f),g):!1},hasClass:function(a,b){return c.hasAttrValue(a,"className",b)},hasRel:function(a,b){return c.hasAttrValue(a,"rel",b)},indexOf:Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b)}:function(a,b){var c,g;c=0;for(g=a.length;c<g;c++)if(a[c]===b)return c;return-1},isArray:function(a){return"array"===c.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},jsonp:function(a){var b=
document.getElementsByTagName("script")[0];a=c.createEl("script",{type:"text/javascript",src:a});b.parentNode.insertBefore(a,b)},map:function(a,b){var g=[];c.each(a,function(a,c){void 0!==a&&(g[c]=b(a))});return g},on:function(){var a;return function(b,g,f){var h,n;if(1===arguments.length)a=b;else{if(2===arguments.length){if(!a)return;f=g;g=b;b=a}try{h=b["on"+g]}catch(d){}"function"===typeof h&&(b["on"+g]=c.bind(function(a){a=a||window.event;var g=h.apply(b,arguments);this.exceptionLogger(function(){return a?
(void 0!==g&&!1!==a.returnValue&&(a.returnValue=g),c.isDefaultPrevented(a)&&"function"===c.type(a.preventDefault)&&a.preventDefault(),a.returnValue):g})()},this));n=c.exceptionLogger(function(){if(a.enabled())return f.apply(null,arguments)});b.addEventListener?b.addEventListener(g,n,!1):b.attachEvent&&b.attachEvent("on"+g,n)}}}(),position:function(a){var b,g=0,c=0,h=0,n=0;if(!a.offsetParent)return!1;b=a;do g+=b.offsetLeft,c+=b.offsetTop,b=b.offsetParent;while(b);b=a;do h+=b.scrollLeft,n+=b.scrollTop,
b=b.parentNode;while(b&&b!==document.body);return{x:g-h,y:c-n}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},ready:function(){var a=!1,b=[],g=!1,f,h,n,d,e;document.addEventListener?n=function(){document.removeEventListener("DOMContentLoaded",n,!1);e()}:document.attachEvent&&(d=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",d),e())});f=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return e();
if(document.addEventListener)document.addEventListener("DOMContentLoaded",n,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",d);var b=!1;try{b=null===window.frameElement}catch(j){}document.documentElement.doScroll&&b&&h()}c.on(window,"load",e)}};h=function(){if(!g){try{document.documentElement.doScroll("left")}catch(a){setTimeout(c.exceptionLogger(h),1);return}e()}};e=function(){if(!g){if(!document.body)return setTimeout(c.exceptionLogger(e),13);g=!0;b&&(c.each(b,function(a){a()}),
b=null)}};return function(a){f();g?a():b.push(a)}}(),reformatKeys:function(a){var b,g,f=function(a){return"_"+a.toLowerCase()};for(b in a)g=b.replace(/([A-Z])/g,f),"object"===c.type(a[b])&&(a[b]=c.reformatKeys(a[b])),g!==b&&(a[g]=a[b],delete a[b]);return a},removeClass:function(a,b){if(c.hasClass(a,b)){var g,f,h=c.attrValues(a,"className");g=0;for(f=h.length;g<f;g++)h[g]===b&&delete h[g];a.className=h.join(" ")}},request:function(a,b,g){var f,h;g=c.extend({fn:c.noop,"return":!1,timeout:null},g);"string"===
typeof g.fn?b=c.extend(b,{jsonp:g.fn}):"function"===typeof g.fn&&(f=c.destructing(g.fn),h=c.uniqid("vglnk_jsonp_"),b=c.extend(b,{jsonp:h}),window[h]=c.exceptionLogger(function(){f.apply(this,arguments);window[h]=void 0}),null!==g.timeout&&setTimeout(c.exceptionLogger(f),g.timeout));b=c.extend({format:"jsonp"},b);b=c.toQuery(b);a=a+(b.length?"?":"")+b;return g["return"]?a:c.traits.cors&&!1!==c.cors(a)?!0:c.jsonp(a)},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,
0)}catch(b){var g,c,h=[];g=0;for(c=a.length;g<c;g++)h[g]=a[g];return h}},toQuery:function(a){var b,g="";for(b in a)null!==a[b]&&void 0!==a[b]&&(g+="\x26"+encodeURIComponent(b)+"\x3d"+encodeURIComponent(a[b]));return g.substr(1)},transmitsPII:function(a){return c.containsPII(a+" "+document.referrer)},updateUrl:function(a,b){return c.extend(c.createA(a),b).href},uniqid:function(){var a=0;return function(b){return(b||"")+(new Date).getTime()+a++}}()});c.traits={basicCompatibility:!(c.browser.blackberry||
c.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!c.browser.ios,jsRedirectSetsReferrer:c.browser.aol||!(c.browser.ie||c.browser.opera),quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var e,p,o,k=function(a){var b=a.previousSibling,g=a.nextSibling,f=["",a.textContent,""],h=function(a,b,g){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");g=g.replace(/\s+/g," ");a=a.replace(/^\s+/,
"");" "===b.substr(0,1)&&(b=b.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===b.substr(b.length-1,1)&&(b=b.substr(0,b.length-1),g=(" "!==g.substr(0,1)?" ":"")+g);g=g.replace(/\s+$/,"");return[a,b,g]};void 0!==f[1]&&(f[0]=b&&3===b.nodeType?b.data:"",f[2]=g&&3===g.nodeType?g.data:"",f=h.apply(this,f),""!==f[0]&&""!==f[2]&&(f[0]=f[0].split(" ").reverse().slice(0,10+(" "===f[0].substr(f[0].length-1,1)?1:0)).reverse().join(" "),f[2]=f[2].split(" ").slice(0,10).join(" "),a={type:"context",itype:(c.cache(a,
"params")||{}).type,before:f[0],after:f[2],txt:f[1],loc:location.href,out:c.getActualHref(a),v:2},l.log("info",c.toQuery(a))))},m={};c.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};var x=c.exceptionLogger(function(){var a=!0===window.document.__v5k;window.document.__v5k=!0;a||(this.initLibEvents(),this.initNamespace(),this.initOptions(),c.exceptionLogger(c.bind(this.logException,this),!e.dev),this.initProcessors(),this.initDRApi(),this.initApi(),this.enabled()&&(this.initLegacyCallbacks(),
this.ping()))}),s=[],q,u=1,y=[],w=function(){var a=[];q=null;c.each(y,function(b){var g,f=b[0];g=b[1];var h=b[2];if(f=window.vglnk&&window.vglnk[f+"_plugin"]){if((b="function"===c.type(f.setup)?f.setup:null)&&!h){var h=c.clone(c),n=g.key;b(g,h,o,function(){if(n){var a=c.toArray(arguments);a.unshift("custom",n);l.log.apply(this,a)}})}g&&1===g.mode?delete g.mode:(g="function"===c.type(f.run)?f.run:c.noop(),g())}else a.push(b)});y=a;0<y.length&&(q=setTimeout(c.exceptionLogger(w),Math.min(Math.max(Math.pow(2,
++u),100),5E3)))},z=function(a,b){return function(){y.push([a,b,!0]);u=1;clearTimeout(q);w()}},A=c.canonicalizeHostname(document.location),E=c.generateNodeFilter({rels:["norewrite","noskim"],custom:function(a){var b,g="";try{b=a.hostname,g=a.protocol,b.charAt(0)}catch(f){return!0}""!==b&&(b=c.canonicalizeHostname(a));return""===b||A===b||!g.match(/^https?:$/i)||e.norewrite[b]||!(e.rewrite_original||c.cache(a,"type"))}}),t,B=!1,C={},F=!1,D=[],b=function(a){if(void 0===a)return D;"function"===c.type(a)&&
(D.push({id:c.uniqid(),fn:a}),F&&this.initLinks())};b(function(){F=!0});l={api:function(a,b,g){a=e.api_url+"/"+a;b=c.extend({cuid:e.cuid,key:e.key,drKey:e.key?null:e.dr_key,loc:location.href,subId:e.sub_id,v:1},b);b.subId&&b.key!==e.key&&(b.subId=null);return c.request(a,b,g)},addEventListener:function(a,b){this.fire(a,b)},click:function(a,b){var g,f,h,n,d=c.context(a)||window;b=a.target||b;b=!b||b===d.name||"_top"===b&&d.top===d||"_parent"===b&&d.parent===d?"_self":b;"_self"===b?h=d:c.traits.crossWindowCommunication&&
c.traits.jsRedirectSetsReferrer?(f=d.open("",b),f.focus(),h=f):h=void 0;if("_self"!==b&&(!c.traits.crossWindowCommunication||!c.traits.jsRedirectSetsReferrer))n="go";else try{if(void 0===h.document)throw!0;n="jsonp"}catch(m){n="go"}g=c.destructing(c.bind(function(){e.time_click&&arguments.length&&this.logTime("clk");var g=c.toArray(arguments);g.unshift(a,h,b);this.onApiClick.apply(this,g)},this));c.cache(this,"link","string"===typeof a?a:c.getActualHref(a));if("string"===typeof a&&(a=c.createA(a,
b),!this.processLink(a))||!e.enabled)return g();f=this.clickParams(a,n);this.logTime();e.log_context&&k(a);if("go"===n)this.redirect(this.api("click",f,{"return":!0}),d,h,b);else if(h===d)this.api("click",f,{fn:g,timeout:e.click_timeout});else{if(c.contextIsAncestor(d,h))return this.redirect(c.getActualHref(a),d,h,b);g=c.exceptionLogger(g);setTimeout(function(){g()},e.click_timeout);h.document.open();h.callback=g;h.document.write("\x3chtml\x3e\x3chead\x3e\x3ctitle\x3e"+c.getActualHref(a)+'\x3c/title\x3e\x3cscript type\x3d"text/javascript" src\x3d"'+
this.api("click",f,{fn:"callback","return":!0})+'"\x3e\x3c/script\x3e\x3c/head\x3e\x3c/html\x3e');h.document.close()}},clickParams:function(a,b){var g=c.extend(c.cache(a,"params"),{format:b,libId:e.library_id,out:c.getActualHref(a),ref:window.document.referrer||null,reaf:e.reaffiliate||null,title:window.document.title,txt:a.innerHTML});128<g.txt.length&&(g.txt=g.txt.replace(/<[^>]+>/g,""),g.txt=128<g.txt.length?g.txt.substr(0,125)+"...":g.txt);return g},enabled:function(){if(e.enabled&&p!==window&&
window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))e.enabled=!1;return e.enabled},expose:function(a,b){if(b=b||this[a])"function"===typeof b?b=c.exceptionLogger(c.bind(b,this)):"object"===typeof b&&(b=c.clone(b)),o[a]||(o[a]=b)},fire:function(a,b){a=a.toLowerCase();var g=m[a]||{fired:!1,listeners:[]};"function"===typeof b?g.fired?b({type:a}):g.listeners.push(b):(g.fired=!0,c.each(g.listeners,function(b){"function"===typeof b&&b({type:a})}),g.listeners=[]);m[a]=g},handleRightClick:function(a,
b){if(e.rewrite_modified&&a&&b)switch(b){case "setup":c.cache(a,"href")||c.cache(a,"href",a.href);a.href=this.api("click",this.clickParams(a,"go"),{"return":!0});setTimeout(c.exceptionLogger(c.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":a.href=c.cache(a,"href"),c.cache(a,"href",null)}},harmony:function(a){return e.harmony_level<=a},init:x,initApi:function(){var a,b={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(b[a]=window.vglnk[a]);o=
p[d]=c.noop;this.expose("click");this.expose("link",function(a){"element"===c.type(a)&&a.href&&(l.initContext(c.context(a)),l.processLink(a))});this.expose("$",c.clone(c));this.expose("api");this.expose("opt");this.expose("registerProcessor",function(){if(0<arguments.length)return l.registerProcessor.apply(l,arguments)});c.extend(o,o===window.vglnk?b:{})},initContext:function(a){if(void 0===a)return s;a&&!c.contains(s,a)&&(s.push(a),this.initLinks(a),this.initEvents(a))},initDRApi:function(){var a=
!1;window.DrivingRevenue=c.exceptionLogger(c.destructing(c.bind(function(){a=!0;e.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));c.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(b){window.DrivingRevenue=void 0}})},initEvents:function(a){var b={left:l.onClick,right:l.onContextmenu},g={left:c.noop,right:c.noop},f=c.traits.windowLevelHandlers?a:a.document,h=function(f){f=f||a.event;if((f=c.eventLink(f))&&!c.cache(f,"evented"))d(f,l.harmony(c.harmony.LINK_LEVEL_EVENTS)?
b:g),c.cache(f,"evented",!0)},d=function(a,b){c.on(a,"click",c.bind(b.left,l));c.on(a,"contextmenu",c.bind(b.right,l))};c.on(f,"copy",c.bind(l.onCopy,l));c.on(f,"mousedown",h);if(l.harmony(c.harmony.LINK_LEVEL_EVENTS))c.on("DOMReady",function(){c.each(a.document.links,function(a){c.on(a,"mousedown",h)})});(!c.traits.quirksMode||l.harmony(c.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&d(f,b)},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",
vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)void 0!==window[a]&&(o[b[a]]=window[a],"vglnk_domain"===a&&(o[b[a]]+="/api"))},initLegacyCallbacks:function(){var a,b={vl_cB:c.bind(this.onApiClick,this),vl_disable:function(){e.enabled=!1}};for(a in b)window[a]=b[a]},initLibEvents:function(){c.on(l);c.ready(c.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var b=c.bind(function(a){c.each(c.toArray(a.document.links),c.bind(this.processLink,this))},this);void 0===a?c.each(this.initContext(),
b):b(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(d="vglnk");var a=window,b=d.split("."),g;for(d=b.pop();0<b.length;)g=b.shift(),a[g]=a[g]||{},a=a[g];p=a;o=p[d]=p[d]||{}},initOptions:function(){var a;this.initLegacyOptions();e=c.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:c.traits.basicCompatibility,key:null,partner:null,sub_id:null,reaffiliate:!1,harmony_level:0,rewrite_original:!0,rewrite_modified:!1}),
e,o,{click_timeout:1E3,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},plugins:{link_affiliation:{},modified_clicks:{}},time_click:!1,time_ping:!1,testing_js:[]});for(a in e)"_plugin"===a.substr(-7)&&delete e[a]},initPlugins:function(a){for(var b in a)"object"===typeof a[b]&&!1!==a[b].enabled&&(y.push([b,a[b]]),1===a[b].mode&&this.expose("init_"+b,z(b,a[b])));w()},initProcessors:function(){this.registerProcessor(function(a){var b;b=c.createA(e.api_url);if("/api/click"===
a.pathname&&(a.hostname===b.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))b=c.fromQuery(a.search),void 0!==b.out&&(a.href=b.out,delete b.out,c.cache(a,"params",b))});this.registerProcessor(function(a){e.nofollow[a.href]&&!c.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&c.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target=
"_blank")})},isRewritable:function(a){return E(a,{ancestors:!1})},log:function(a,b,g,f){var h,d=c.toQuery({nocache:c.uniqid()});h="pixel.gif";if("custom"===a)d+="\x26"+c.toQuery({key:b,type:g}),c.each("array"===c.type(f)?f:[f],function(a){c.each(["e","i","o"],function(b){delete a[b]});d+="\x26"+c.toQuery(a)});else{d+="\x26"+c.toQuery({key:e.key,drKey:e.key?null:e.dr_key});if("time"===a)h="time.gif",a={libId:e.library_id,time:g,type:b};else if("exception"===a)a={e:b,o:g};else if("info"===a)a={i:b};
else return;d+="\x26"+c.toQuery(a)}h=e.api_url+"/"+h+"?"+d;c.transmitsPII(h)||(c.createEl("img").src=h)},logException:function(a){if(e.debug){var b={link:c.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?b.message=a:b=c.extend(b,a);this.log("exception",a,c.toQuery(b))}},logTime:function(a){0===arguments.length?t=(new Date).getTime():this.log("time",a,(new Date).getTime()-t)},onApiClick:function(a,b,g,f,h){var d=f||c.getActualHref(a),k=c.bind(function(){this.redirect(d,
c.context(a),b,g)},this);"object"===typeof h&&(h.tracking||h.image)?(f=c.createEl(h.tracking?"iframe":"img",{src:h.tracking||h.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(f),setTimeout(c.exceptionLogger(k),h.timeout||e.hop_timeout)):k()},onApiPing:function(a,b,g,f,h,d){e.rewrite_original=!1;h=c.reformatKeys(h||{});var k,m;f=function(a){var b={},g=function(a){c.isArray(a)?b[a[0]]=a[1]:b[a]=1};c.isArray(a)&&c.each(a,g);return b};m=c.extend(e.plugins,h.plugins);e=c.extend(e,
h);delete e.plugins;e.library_id=a;e.click_timeout=b;e.time_ping&&this.logTime("png");"array"===c.type(e.testing_js)&&0<e.testing_js.length&&c.each(e.testing_js,function(a){c.jsonp(a)});c.extend(e.norewrite,f(g));c.extend(e.nofollow,f(d));for(k in e)"on"===k.toLowerCase().substr(0,2)&&(2<k.length&&"function"===c.type(e[k]))&&(c.on(l,k.toLowerCase().substr(2),c.bind(e[k],window)),delete e[k]);this.initPlugins(m);this.initContext(window);this.fire("libready")},onClick:function(a){a=a||window.event;
var b=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,g=a.which&&1===a.which||0===a.button,f=c.eventLink(a);if(f&&this.isRewritable(f)&&!b&&g&&!c.isDefaultPrevented(a))return this.click(f),c.preventDefault(a)},onContextmenu:function(a){(a=c.eventLink(a||window.event))&&this.isRewritable(a)&&this.handleRightClick(a,"setup")},onCopy:function(){var a,b,g,f,h=[];if(window.getSelection){g=window.getSelection();a=0;for(b=g.rangeCount;a<b;a++){try{f=g.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,
"\n")}catch(d){}0<f.length&&128>=f.length&&h.push(f)}}c.each(h,function(a){l.log("info",c.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,b){void 0!==b&&void 0!==this.publicOptions()[a]&&(e[a]=b);return e[a]},ping:function(){if(!B&&(e.key||e.dr_key)){var a={ref:document.referrer||null};B=!0;c.transmitsPII(this.api("ping",a,{"return":!0}))||(this.logTime(),this.api("ping",a,{fn:c.bind(this.onApiPing,this)}))}},processLink:function(a){if(this.isRewritable(a)){var b=c.cache(a,
"processors")||{};c.each(this.registerProcessor(),function(g){b[g.id]||g.fn(a);b[g.id]=!0});c.cache(a,"processors",b);return a}},publicOptions:function(a){"object"===c.type(a)&&(C=a);return c.extend({},C)},redirect:function(a,b,g,f){!c.traits.crossWindowCommunication&&!g?(f=b.open(a,f),f.focus()):c.traits.jsRedirectSetsReferrer?setTimeout(c.exceptionLogger(function(){!g||g===b?b.location=a:c.contextIsAncestor(b,g)?g.location=a:g.location.replace(a)}),0):("_blank"===f&&(f=c.uniqid("win_")),f=c.createA(a,
f),f.rel="norewrite",b.document.body.appendChild(f),f.click(),f.parentNode.removeChild(f))},registerProcessor:b};l.init();try{delete window.vglnk_self}catch(g){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};window.vglnk.link_affiliation_plugin=function(){var d;return{setup:function(l,c,i){d=i},run:function(){d.opt("rewrite_original",!0)}}}();window.vglnk=window.vglnk||{};
window.vglnk.modified_clicks_plugin=function(){var d;return{setup:function(l,c,i){d=i},run:function(){d.opt("rewrite_modified",!0)}}}();window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(){var d,l,c={key:null},i={init:function(){d.each(this.getDRSearchForms(),function(c){if(!d.cache(c,"evented")){var l=i.getInput(c),o=function(){l.value||d.css(l,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};d.cache(c,"evented",!0);c.onsubmit=null;l.onfocus=null;l.onblur=null;d.on(l,"focus",function(){d.css(l,{"background-image":"none"})});d.on(l,"blur",o);o();d.on(c,"submit",function(d){i.onSubmit(d,c)})}})},getDRSearchForms:function(){var c=
[];d.each(document.getElementsByTagName("form"),function(d){i.getInput(d)&&d.id.match(/^DR-ebay-search(CSS|2)?$/i)&&c.push(d)});return c},getInput:function(c){return c.p||c.q2},onSubmit:function(e,p){e=e||window.event;var o="http://shop.ebay.com/i.html?"+d.toQuery({_nkw:i.getInput(p).value}),o=d.createA(o,"_blank");d.cache(o,"params",{key:c.key});l.click(o);return d.preventDefault(e)}};return{setup:function(e,i,o){d=i;l=o;c=d.extend(c,e)},run:function(){c.key&&(i.init(),d.on("DOMReady",d.bind(i.init,
i)))}}}();window.vglnk=window.vglnk||{};window.vglnk.page_harmony_plugin=function(){var d,l,c={level:null};return{setup:function(i,e,p){d=i;l=p;c=d.extend(c,e)},run:function(){var d=parseInt(c.level,10);isFinite(d)&&l.opt("harmony_level",d)}}}();window.vglnk=window.vglnk||{};
window.vglnk.partner_integration_plugin=function(){var d,l,c={eb_campaign:5337208431,eb_cid:null,eb_gid:null,eb_group:null,eb_pct:0,eb_rotation:"711-53200-19255-0"},i=/(^|\.)ebay\.com$/,e=/(^|\.)rover\.ebay\.com$/,p={injectPixel:function(){if(c.eb_cid&&c.eb_campaign&&c.eb_rotation&&"number"===d.type(c.eb_gid)&&isFinite(c.eb_gid)&&0<=c.eb_gid){var e,k="//rover.ebay.com/roverimp/1/"+encodeURIComponent(c.eb_rotation)+"/1",m={campid:c.eb_campaign,ff19:c.eb_cid,ff20:c.eb_gid,mpt:Math.floor(99999999*Math.random()),
pub:5574713606,toolid:2E4};e=d.createEl("img",{src:k+"?"+d.toQuery(m)},{border:"none",height:0,width:0,position:"absolute",zIndex:-1});d.on("DOMReady",function(){document.body&&document.body.appendChild(e)})}},expandTruncatedUrl:function(c,d){var e;e=d.textContent||d.innerText;if(e&&(-1!==e.indexOf("...")||-1!==e.indexOf("\u2026"))){var i=e.split("...")[0].split("\u2026")[0],l=c.replace(/^http:\/\//i,"");e=i.length<c.length&&c.substr(0,i.length)===i||i.length<l.length&&l.substr(0,i.length)===i&&-1!==
e.indexOf("/")}else e=void 0;if(e){for(;e=d.firstChild;)d.removeChild(e);d.appendChild(document.createTextNode(c))}},shouldBeUnlinked:function(c,k){var m=d.canonicalizeHostname(c);return i.test(m)&&("inserted"===d.cache(k,"type")||!e.test(m))},unlink:function(c){var e,i,l=!0,p=d.getActualHref(c);if(this.shouldBeUnlinked(p,c)){e=document.createDocumentFragment();if(c.parentNode){for(;i=c.firstChild;)l=l&&3===i.nodeType,e.appendChild(i);l&&this.expandTruncatedUrl(p,e);c.parentNode.insertBefore(e,c);
c.parentNode.removeChild(c)}d.cache(c,"unlinked",!0)}}};return{setup:function(e,k,i){d=k;l=i;c=d.extend(c,e);null===c.eb_group&&(c.eb_group=c.eb_gid/10<c.eb_pct?1:0)},run:function(){p.injectPixel();1===c.eb_group&&l.registerProcessor(d.bind(p.unlink,p))}}}();window.vglnk=window.vglnk||{};
window.vglnk.product_linker_plugin=function(){var d,l,c,i={},e,p,o=null,k={},m,x=0,s=0,q=0,u=0,y={setup:function(w,z,A,E){d=z;l=A;c=E;i=d.extend({cat:null,platform:null,key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,product_source:null,proximity:null,same_proximity:100,scope:null,type:null,ui:!0},w);if(i.key){d=d.extend(d,{matches:window.vglnk.Sizzle.matchesSelector||function(){return!0},select:window.vglnk.Sizzle||function(){return[]}});e={bbp:{id_finder:["li",
/^post-(\d+)$/],scope:"li .post"},hdlr:{id_finder:["div",/^post_(\d+)$/],scope:".post-content-area"},ipb:{id_finder:["div",/^post_id_(\d+)$/],scope:".post_body .post"},phpb:{id_finder:["div.post",/^p(\d+)$/],scope:".postbody .content, .postbody .signature"},ubb:{id_finder:["a",/^Post(\d+)$/,"name"],scope:".post_inner *[id^\x3d'body'], .post_inner .signature"},vb3:{id_finder:["div[id], table[id]",/^post(\d+)$/],scope:"td[id^\x3d'td_post_'] div[id^\x3d'post_message_'],td[id^\x3d'td_post_'] div[id^\x3d'post_message_'] ~ div:not([class])"},
vb4:{id_finder:["li",/^post_(\d+)$/],scope:".postbody .content, .postbody .signature, .post-content, ul.conversation-list .list-item-body"},wppr:{id_finder:["div",/^post-(\d+)$/],scope:null}}[i.platform]||{};var t={timing:!1,data:i.link_phrases?!1:i.link_urls},B=function(c){var b=m.test(c.data),g=c.parentNode;if(b)for(var a=c,j,e,f,b=function(a,b){var g,c,f,j,h,e,n,G,l,m,D=function(b){l.parentNode.insertBefore(a,l);l.parentNode.removeChild(l);return b};l=d.createEl("span");a.parentNode.insertBefore(l,
a);l.appendChild(a);m=d.geometry(l);if(i.proximity||i.same_proximity)for(e in k)if((n=k[e].links)&&!(k[e]===b&&!i.same_proximity||k[e]!==b&&!i.proximity)){G=k[e]===b?Math.max(i.same_proximity,i.proximity):i.proximity;g=0;for(c=n.length;g<c;g++){h=n[g].segments;f=0;for(j=h.length;f<j;f++){var q=h[f].geometry,v=m,o=G,q=d.extend({},q);q.x1-=o;q.y1-=o;q.x2+=o;q.y2+=o;if(q.x1<v.x2&&q.x2>v.x1&&q.y1<v.y2&&q.y2>v.y1)return D(!1)}}}return D(!0)};a&&a.data&&Boolean(e=a.data.match(m));){j=e[0];f=e.slice(1).join("");
c=k[f.toLowerCase()];j=a.data.indexOf(j)+j.length-f.length;0<j&&(a=a.splitText(j));j=a.length<=f.length?null:a.splitText(f.length);f&&!c&&(c={url:f.match(/^https?:\/\//i)?f:"http://"+f,type:"U"});var h;if(h=f){var n=h=void 0;h=!c||!i.per_phrase||!c.count||c.count<i.per_phrase;n=!i.per_page||x<i.per_page;h=h&&n&&b(a,c)}if(h&&(h=c,n=void 0,n=d.createEl("a"),n.innerHTML=f.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"\x3cspan\x3e$1\x3c/span\x3e"),n.className="vglnk",d.cache(n,"type","inserted"),d.cache(n,"phrase",
f),i.ui&&(n.title="Link added by VigLink"),p.initLink(n,h),f=n,!d.cache(f,"unlinked"))){"U"===c.type?u++:"L"===c.type.toUpperCase()?s++:q++;g.insertBefore(f,a);g.removeChild(a);var a=c,l=n=h=void 0,o=void 0,t={el:f,segments:[]};f=f.getElementsByTagName("span");var w={els:[]};h=0;for(n=f.length;h<n;h++)l=f[h],void 0===o||l.offsetTop===o.offsetTop?w.els.push(l):(t.segments.push(w),w={els:[l]}),o=l;w.geometry=d.geometry.apply(d,w.els);t.segments.push(w);a.links=a.links||[];a.links.push(t);c.count++;
x++}a=j}},C=d.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(c){return d.matches(c,"a[href]")}}),F=function(c){var b;if(c){if(C(c,{ancestors:!1,self:!0}))for(b=c.firstChild;b;)c=b.nextSibling,1===b.nodeType?F(b):3===b.nodeType&&B(b),b=c}else d.each(d.select(i.scope),function(b){C(b,{ancestors:!0,self:!1})&&F(b)})};p={addPhrasesToMatcher:function(c){var b=
"";"regexp"===d.type(c)?b=c.source:"array"===d.type(c)&&(b="(?:^|[\\s\"'\\(])("+d.map(c,d.escapeRegExp).join("|")+")(?\x3d\\s|\\W*$|\\W{2})");""!==b&&(m=RegExp(m?"(?:"+b+"|"+m.source+")":b,"i"))},focusLink:function(c){c.id||(c.id=d.uniqid("vl-link-"));location.href.hash="#"+c.id;window.scrollBy(0,-150)},getPhrases:function(c){l.api("insert",d.extend(p.getPartnerParams(),{cat:i.cat,mode:i.mode,pt:i.platform,ps:i.product_source,i:c?c.join("|"):null,u:location.href,type:i.type}),{fn:d.bind(p.onInsertApi,
p)})},getPartnerParams:function(){var c,b,g=l.opt("partner"),a={};for(c in g)break;if(c)for(b in g[c])a[c+"_"+b]=g[c][b];return a},getPostIDs:function(){var c=[],b=e?e.id_finder:null;b&&d.each(d.select(b[0]),function(g){var a=b[2]||"id";(g=g[a]?g[a].match(b[1]):null)&&c.push(g[1])});return c.length?c:null},initLink:function(c,b,g){if(g=i.link_target||g)c.target=g;c.rel="nofollow";c.href||(c.href=b.url);d.cache(c,"params",{exp:o,key:i.key,mid:b.mid,type:b.type||null});d.cache(c,"href",c.href);l.link(c)},
insertLinks:function(c){t=d.extend(t,c);t.timing&&(t.data&&m)&&(F(),p.log())},loadPhrases:function(c){var b,g,a,j=[];b=0;for(g=c.length;b<g;b++)a=c[b],a.phrase&&a.url&&(a.phrase=a.phrase.toLowerCase(),k[a.phrase]||(j.push(a.phrase),k[a.phrase]={count:k[a.phrase]?k[a.phrase].count:0,phrase:a.phrase,mid:a.mid,url:a.url,type:a.type||""}));0<j.length&&this.addPhrasesToMatcher(j);this.insertLinks({data:!0})},log:function(){var d,b,g={heavy:[],lite:[]},a=function(a,b){return b.split(",")[0]-a.split(",")[0]};
for(d in k)b=parseInt(k[d].count,10),0<b&&(b=[b,d.replace(/\|/g,"%7C")].join(),g["L"===k[d].type.toUpperCase()?"lite":"heavy"].push(b));g.lite.sort(a);g.heavy.sort(a);c("insert",[{ct:x,cl:s,ch:q,cu:u,exp:o},{pl:g.lite.join("|")},{ph:g.heavy.join("|")}])},onInsertApi:function(c){"object"===d.type(c)&&(o=c.exp,c.results&&this.loadPhrases(c.results))},setup:function(){var c=d.bind(function(){this.getPhrases(this.getPostIDs())},this);i.scope=i.scope||e.scope||"body";i.link_urls&&this.addPhrasesToMatcher(RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()\x3c\x3e]+|\\((?:[^\\s()\x3c\x3e]|(?:\\([^\\s()\x3c\x3e]+\\)))*\\))+(?:\\((?:[^\\s()\x3c\x3e]|(?:\\([^\\s()\x3c\x3e]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,\x3c\x3e?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))",
"i"));if(i.link_phrases)if(!i.platform||"full"===i.platform)c();else d.on("DOMReady",c)}};p.setup()}else y.run=d.noop},run:function(){d.on("DOMReady",function(){p.insertLinks({timing:!0})})}};return y}();window.vglnk=window.vglnk||{};
window.vglnk.link_optimization_plugin=function(){var d,l,c={},i,e,p={};return{setup:function(o,k,m){d=k;l=m;c=d.extend({platform:null},o);d=d.extend(d,{select:window.vglnk.Sizzle||function(){return[]}});i={bbp:{id_finder:["li",/^post-(\d+)$/]},hdlr:{id_finder:["div",/^post_(\d+)$/]},ipb:{id_finder:["div",/^post_id_(\d+)$/]},phpb:{id_finder:["div.post",/^p(\d+)$/]},ubb:{id_finder:["a",/^Post(\d+)$/,"name"]},vb3:{id_finder:["td",/^td_post_(\d+)$/]},vb4:{id_finder:["li",/^post_(\d+)$/]},wppr:{id_finder:["div",
/^post-(\d+)$/]}}[c.platform]||{};var x=function(c){var e=c.textContent||c.innerText;c=d.canonicalizeHostname(c);e=d.createEl("a",{href:e});return d.canonicalizeHostname(e)===c},s=d.generateNodeFilter({classes:["nooptimize"],rels:["nooptimize"],custom:function(c,e){return e?Boolean(d.cache(c,"type")):!1}});e={getLinks:function(k){l.api("optimize",{pt:c.platform,i:k?k.join("|"):null,u:location.href},{fn:d.bind(e.onOptimizeApi,e)})},getPostIDs:function(){var c=[],e=i?i.id_finder:null;e&&d.each(d.select(e[0]),
function(d){var k=e[2]||"id";(d=d[k]?d[k].match(e[1]):null)&&c.push(d[1])});return c.length?c:null},onOptimizeApi:function(c){"object"===d.type(c)&&"object"===d.type(c.optLinks)&&(p=c.optLinks,l.registerProcessor(d.bind(this.optimizeLink,e)))},optimizeLink:function(c){var e=p[c.href];if(e&&s(c)){var k=c.textContent||c.innerText,i;if(!(i=c.href===k))x(c)?(i=d.fromQuery(c.search),i=d.find(i,function(c){return c===k})):i=!1;if(i){i=e.optLink;for(var l;l=c.firstChild;)c.removeChild(l);c.appendChild(document.createTextNode(i))}else if(x(c))return;
d.cache(c,"params",{type:"LO",origOutId:e.pcid+":"+e.linkId});c.href=e.optLink}},setup:function(){var e=d.bind(function(){this.getLinks(this.getPostIDs())},this);if(!c.platform||"full"===c.platform)e();else d.on("DOMReady",e)}};e.setup()},run:function(){}}}();
(function(){function d(b,c,a,j,d,f){d=0;for(var h=j.length;d<h;d++){var e=j[d];if(e){for(var k=!1,e=e[b];e;){if(e.sizcache===a){k=j[e.sizset];break}1===e.nodeType&&!f&&(e.sizcache=a,e.sizset=d);if(e.nodeName.toLowerCase()===c){k=e;break}e=e[b]}j[d]=k}}}function l(b,c,a,j,d,f){d=0;for(var h=j.length;d<h;d++){var e=j[d];if(e){for(var i=!1,e=e[b];e;){if(e.sizcache===a){i=j[e.sizset];break}if(1===e.nodeType)if(f||(e.sizcache=a,e.sizset=d),"string"!==typeof c){if(e===c){i=!0;break}}else if(0<k.filter(c,
[e]).length){i=e;break}e=e[b]}j[d]=i}}}var c=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,i=0,e=Object.prototype.toString,p=!1,o=!0;[0,0].sort(function(){o=!1;return 0});var k=function(b,g,a,j){a=a||[];var d=g=g||document;if(1!==g.nodeType&&9!==g.nodeType)return[];if(!b||"string"!==typeof b)return a;var f,h,i,l,o,p=!0,q=k.isXML(g),r=[],s=b;do if(c.exec(""),f=c.exec(s))if(s=f[3],r.push(f[1]),f[2]){l=f[3];break}while(f);
if(1<r.length&&x.exec(b))if(2===r.length&&m.relative[r[0]])h=D(r[0]+r[1],g);else for(h=m.relative[r[0]]?[g]:k(r.shift(),g);r.length;)b=r.shift(),m.relative[b]&&(b+=r.shift()),h=D(b,h);else if(!j&&(1<r.length&&9===g.nodeType&&!q&&m.match.ID.test(r[0])&&!m.match.ID.test(r[r.length-1]))&&(f=k.find(r.shift(),g,q),g=f.expr?k.filter(f.expr,f.set)[0]:f.set[0]),g){f=j?{expr:r.pop(),set:u(j)}:k.find(r.pop(),1===r.length&&("~"===r[0]||"+"===r[0])&&g.parentNode?g.parentNode:g,q);h=f.expr?k.filter(f.expr,f.set):
f.set;for(0<r.length?i=u(h):p=!1;r.length;)f=o=r.pop(),m.relative[o]?f=r.pop():o="",null==f&&(f=g),m.relative[o](i,f,q)}else i=[];i||(i=h);i||k.error(o||b);if("[object Array]"===e.call(i))if(p)if(g&&1===g.nodeType)for(b=0;null!=i[b];b++)i[b]&&(!0===i[b]||1===i[b].nodeType&&k.contains(g,i[b]))&&a.push(h[b]);else for(b=0;null!=i[b];b++)i[b]&&1===i[b].nodeType&&a.push(h[b]);else a.push.apply(a,i);else u(i,a);l&&(k(l,d,a,j),k.uniqueSort(a));return a};k.uniqueSort=function(b){if(w&&(p=o,b.sort(w),p))for(var c=
1;c<b.length;c++)b[c]===b[c-1]&&b.splice(c--,1);return b};k.matches=function(b,c){return k(b,null,null,c)};k.matchesSelector=function(b,c){return 0<k(c,null,null,[b]).length};k.find=function(b,c,a){var j;if(!b)return[];for(var d=0,f=m.order.length;d<f;d++){var e,i=m.order[d];if(e=m.leftMatch[i].exec(b)){var k=e[1];e.splice(1,1);if("\\"!==k.substr(k.length-1)&&(e[1]=(e[1]||"").replace(/\\/g,""),j=m.find[i](e,c,a),null!=j)){b=b.replace(m.match[i],"");break}}}j||(j="undefined"!==typeof c.getElementsByTagName?
c.getElementsByTagName("*"):[]);return{set:j,expr:b}};k.filter=function(b,c,a,j){for(var d,f,e=b,i=[],l=c,o=c&&c[0]&&k.isXML(c[0]);b&&c.length;){for(var p in m.filter)if(null!=(d=m.leftMatch[p].exec(b))&&d[2]){var q,r,s=m.filter[p];r=d[1];f=!1;d.splice(1,1);if("\\"!==r.substr(r.length-1)){l===i&&(i=[]);if(m.preFilter[p])if(d=m.preFilter[p](d,l,a,i,j,o)){if(!0===d)continue}else f=q=!0;if(d)for(var t=0;null!=(r=l[t]);t++)if(r){q=s(r,d,t,l);var u=j^!!q;a&&null!=q?u?f=!0:l[t]=!1:u&&(i.push(r),f=!0)}if(void 0!==
q){a||(l=i);b=b.replace(m.match[p],"");if(!f)return[];break}}}if(b===e)if(null==f)k.error(b);else break;e=b}return l};k.error=function(b){throw"Syntax error, unrecognized expression: "+b;};var m=k.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(?:(['"])(.*?)\3|(#?(?:[\w\u00c0-\uFFFF\-]|\\.)*)|)|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,
CHILD:/:(only|nth|last|first)-child(?:\(\s*(even|odd|(?:[+\-]?\d+|(?:[+\-]?\d*)?n\s*(?:[+\-]\s*\d+)?))\s*\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(b){return b.getAttribute("href")}},relative:{"+":function(b,c){var a="string"===typeof c,d=a&&!/\W/.test(c),a=a&&!d;d&&(c=c.toLowerCase());for(var d=0,e=
b.length,f;d<e;d++)if(f=b[d]){for(;(f=f.previousSibling)&&1!==f.nodeType;);b[d]=a||f&&f.nodeName.toLowerCase()===c?f||!1:f===c}a&&k.filter(c,b,!0)},"\x3e":function(b,c){var a,d="string"===typeof c,e=0,f=b.length;if(d&&!/\W/.test(c))for(c=c.toLowerCase();e<f;e++){if(a=b[e])a=a.parentNode,b[e]=a.nodeName.toLowerCase()===c?a:!1}else{for(;e<f;e++)(a=b[e])&&(b[e]=d?a.parentNode:a.parentNode===c);d&&k.filter(c,b,!0)}},"":function(b,c,a){var j,e=i++,f=l;"string"===typeof c&&!/\W/.test(c)&&(j=c=c.toLowerCase(),
f=d);f("parentNode",c,e,b,j,a)},"~":function(b,c,a){var j,e=i++,f=l;"string"===typeof c&&!/\W/.test(c)&&(j=c=c.toLowerCase(),f=d);f("previousSibling",c,e,b,j,a)}},find:{ID:function(b,c,a){if("undefined"!==typeof c.getElementById&&!a)return(b=c.getElementById(b[1]))&&b.parentNode?[b]:[]},NAME:function(b,c){if("undefined"!==typeof c.getElementsByName){for(var a=[],d=c.getElementsByName(b[1]),e=0,f=d.length;e<f;e++)d[e].getAttribute("name")===b[1]&&a.push(d[e]);return 0===a.length?null:a}},TAG:function(b,
c){if("undefined"!==typeof c.getElementsByTagName)return c.getElementsByTagName(b[1])}},preFilter:{CLASS:function(b,c,a,d,e,f){b=" "+b[1].replace(/\\/g,"")+" ";if(f)return b;f=0;for(var h;null!=(h=c[f]);f++)h&&(e^(h.className&&0<=(" "+h.className+" ").replace(/[\t\n\r]/g," ").indexOf(b))?a||d.push(h):a&&(c[f]=!1));return!1},ID:function(b){return b[1].replace(/\\/g,"")},TAG:function(b){return b[1].toLowerCase()},CHILD:function(b){if("nth"===b[1]){b[2]||k.error(b[0]);b[2]=b[2].replace(/^\+|\s*/g,"");
var c=/(-?)(\d*)(?:n([+\-]?\d*))?/.exec("even"===b[2]&&"2n"||"odd"===b[2]&&"2n+1"||!/\D/.test(b[2])&&"0n+"+b[2]||b[2]);b[2]=c[1]+(c[2]||1)-0;b[3]=c[3]-0}else b[2]&&k.error(b[0]);b[0]=i++;return b},ATTR:function(b,c,a,d,e,f){c=b[1]=b[1].replace(/\\/g,"");!f&&m.attrMap[c]&&(b[1]=m.attrMap[c]);b[4]=(b[4]||b[5]||"").replace(/\\/g,"");"~\x3d"===b[2]&&(b[4]=" "+b[4]+" ");return b},PSEUDO:function(b,g,a,d,e){if("not"===b[1])if(1<(c.exec(b[3])||"").length||/^\w/.test(b[3]))b[3]=k(b[3],null,null,g);else return b=
k.filter(b[3],g,a,1^e),a||d.push.apply(d,b),!1;else if(m.match.POS.test(b[0])||m.match.CHILD.test(b[0]))return!0;return b},POS:function(b){b.unshift(!0);return b}},filters:{enabled:function(b){return!1===b.disabled&&"hidden"!==b.type},disabled:function(b){return!0===b.disabled},checked:function(b){return!0===b.checked},selected:function(b){return!0===b.selected},parent:function(b){return!!b.firstChild},empty:function(b){return!b.firstChild},has:function(b,c,a){return!!k(a[3],b).length},header:function(b){return/h\d/i.test(b.nodeName)},
text:function(b){return"text"===b.type},radio:function(b){return"radio"===b.type},checkbox:function(b){return"checkbox"===b.type},file:function(b){return"file"===b.type},password:function(b){return"password"===b.type},submit:function(b){return"submit"===b.type},image:function(b){return"image"===b.type},reset:function(b){return"reset"===b.type},button:function(b){return"button"===b.type||"button"===b.nodeName.toLowerCase()},input:function(b){return/input|select|textarea|button/i.test(b.nodeName)}},
setFilters:{first:function(b,c){return 0===c},last:function(b,c,a,d){return c===d.length-1},even:function(b,c){return 0===c%2},odd:function(b,c){return 1===c%2},lt:function(b,c,a){return c<a[3]-0},gt:function(b,c,a){return c>a[3]-0},nth:function(b,c,a){return a[3]-0===c},eq:function(b,c,a){return a[3]-0===c}},filter:{PSEUDO:function(b,c,a,d){var e=c[1],f=m.filters[e];if(f)return f(b,a,c,d);if("contains"===e)return 0<=(b.textContent||b.innerText||k.getText([b])||"").indexOf(c[3]);if("not"===e){c=c[3];
a=0;for(d=c.length;a<d;a++)if(c[a]===b)return!1;return!0}k.error(e)},CHILD:function(b,c){var a=c[1],d=b;switch(a){case "only":case "first":for(;d=d.previousSibling;)if(1===d.nodeType)return!1;if("first"===a)return!0;d=b;case "last":for(;d=d.nextSibling;)if(1===d.nodeType)return!1;return!0;case "nth":var a=c[2],e=c[3];if(1===a&&0===e)return!0;var f=c[0],h=b.parentNode;if(h&&(h.sizcache!==f||!b.nodeIndex)){for(var i=0,d=h.firstChild;d;d=d.nextSibling)1===d.nodeType&&(d.nodeIndex=++i);h.sizcache=f}d=
b.nodeIndex-e;return 0===a?0===d:0===d%a&&0<=d/a}},ID:function(b,c){return 1===b.nodeType&&b.getAttribute("id")===c},TAG:function(b,c){return"*"===c&&1===b.nodeType||b.nodeName.toLowerCase()===c},CLASS:function(b,c){return-1<(" "+(b.className||b.getAttribute("class"))+" ").indexOf(c)},ATTR:function(b,c){var a=c[1],a=m.attrHandle[a]?m.attrHandle[a](b):null!=b[a]?b[a]:b.getAttribute(a),d=a+"",e=c[2],f=c[4];return null==a?"!\x3d"===e:"\x3d"===e?d===f:"*\x3d"===e?0<=d.indexOf(f):"~\x3d"===e?0<=(" "+d+
" ").indexOf(f):!f?d&&!1!==a:"!\x3d"===e?d!==f:"^\x3d"===e?0===d.indexOf(f):"$\x3d"===e?d.substr(d.length-f.length)===f:"|\x3d"===e?d===f||d.substr(0,f.length+1)===f+"-":!1},POS:function(b,c,a,d){var e=m.setFilters[c[2]];if(e)return e(b,a,c,d)}}},x=m.match.POS,s=function(b,c){return"\\"+(c-0+1)},q;for(q in m.match)m.match[q]=RegExp(m.match[q].source+/(?![^\[]*\])(?![^\(]*\))/.source),m.leftMatch[q]=RegExp(/(^(?:.|\r|\n)*?)/.source+m.match[q].source.replace(/\\(\d+)/g,s));var u=function(b,c){b=Array.prototype.slice.call(b,
0);return c?(c.push.apply(c,b),c):b};try{Array.prototype.slice.call(document.documentElement.childNodes,0)}catch(y){u=function(b,c){var a=0,d=c||[];if("[object Array]"===e.call(b))Array.prototype.push.apply(d,b);else if("number"===typeof b.length)for(var i=b.length;a<i;a++)d.push(b[a]);else for(;b[a];a++)d.push(b[a]);return d}}var w,z;document.documentElement.compareDocumentPosition?w=function(b,c){return b===c?(p=!0,0):!b.compareDocumentPosition||!c.compareDocumentPosition?b.compareDocumentPosition?
-1:1:b.compareDocumentPosition(c)&4?-1:1}:(w=function(b,c){var a,d,e=[],f=[];a=b.parentNode;d=c.parentNode;var h=a;if(b===c)return p=!0,0;if(a===d)return z(b,c);if(a){if(!d)return 1}else return-1;for(;h;)e.unshift(h),h=h.parentNode;for(h=d;h;)f.unshift(h),h=h.parentNode;a=e.length;d=f.length;for(h=0;h<a&&h<d;h++)if(e[h]!==f[h])return z(e[h],f[h]);return h===a?z(b,f[h],-1):z(e[h],c,1)},z=function(b,c,a){if(b===c)return a;for(b=b.nextSibling;b;){if(b===c)return-1;b=b.nextSibling}return 1});k.getText=
function(b){for(var c="",a,d=0;b[d];d++)a=b[d],3===a.nodeType||4===a.nodeType?c+=a.nodeValue:8!==a.nodeType&&(c+=k.getText(a.childNodes));return c};s=document.createElement("div");q="script"+(new Date).getTime();var A=document.documentElement;s.innerHTML="\x3ca name\x3d'"+q+"'/\x3e";A.insertBefore(s,A.firstChild);document.getElementById(q)&&(m.find.ID=function(b,c,a){if("undefined"!==typeof c.getElementById&&!a)return(c=c.getElementById(b[1]))?c.id===b[1]||"undefined"!==typeof c.getAttributeNode&&
c.getAttributeNode("id").nodeValue===b[1]?[c]:void 0:[]},m.filter.ID=function(b,c){var a="undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id");return 1===b.nodeType&&a&&a.nodeValue===c});A.removeChild(s);A=s=null;s=document.createElement("div");s.appendChild(document.createComment(""));0<s.getElementsByTagName("*").length&&(m.find.TAG=function(b,c){var a=c.getElementsByTagName(b[1]);if("*"===b[1]){for(var d=[],e=0;a[e];e++)1===a[e].nodeType&&d.push(a[e]);a=d}return a});s.innerHTML="\x3ca href\x3d'#'\x3e\x3c/a\x3e";
s.firstChild&&("undefined"!==typeof s.firstChild.getAttribute&&"#"!==s.firstChild.getAttribute("href"))&&(m.attrHandle.href=function(b){return b.getAttribute("href",2)});s=null;if(document.querySelectorAll){var E=k,s=document.createElement("div");s.innerHTML="\x3cp class\x3d'TEST'\x3e\x3c/p\x3e";if(!(s.querySelectorAll&&0===s.querySelectorAll(".TEST").length)){var k=function(b,c,a,d){c=c||document;if(!d&&!k.isXML(c)){var e=/^(\w+$)|^\.([\w\-]+$)|^#([\w\-]+$)/.exec(b);if(e&&(1===c.nodeType||9===c.nodeType)){if(e[1])return u(c.getElementsByTagName(b),
a);if(e[2]&&m.find.CLASS&&c.getElementsByClassName)return u(c.getElementsByClassName(e[2]),a)}if(9===c.nodeType){if("body"===b&&c.body)return u([c.body],a);if(e&&e[3]){var f=c.getElementById(e[3]);if(f&&f.parentNode){if(f.id===e[3])return u([f],a)}else return u([],a)}try{return u(c.querySelectorAll(b),a)}catch(h){}}else if(1===c.nodeType&&"object"!==c.nodeName.toLowerCase()){var f=(e=c.getAttribute("id"))||"__sizzle__",i=c.parentNode,l=/^\s*[+~]/.test(b);e?f=f.replace(/'/g,"\\$\x26"):c.setAttribute("id",
f);l&&i&&(c=c.parentNode);try{if(!l||i)return u(c.querySelectorAll("[id\x3d'"+f+"'] "+b),a)}catch(o){}finally{e||c.removeAttribute("id")}}}return E(b,c,a,d)},t;for(t in E)k[t]=E[t];s=null}}t=document.documentElement;var B=t.matchesSelector||t.mozMatchesSelector||t.webkitMatchesSelector||t.msMatchesSelector,C=!1;try{B.call(document.documentElement,"[test!\x3d'']:sizzle")}catch(F){C=!0}B&&(k.matchesSelector=function(b,c){c=c.replace(/\=\s*([^'"\]]*)\s*\]/g,"\x3d'$1']");if(!k.isXML(b))try{if(C||!m.match.PSEUDO.test(c)&&
!/!=/.test(c))return B.call(b,c)}catch(a){}return 0<k(c,null,null,[b]).length});t=document.createElement("div");t.innerHTML="\x3cdiv class\x3d'test e'\x3e\x3c/div\x3e\x3cdiv class\x3d'test'\x3e\x3c/div\x3e";t.getElementsByClassName&&0!==t.getElementsByClassName("e").length&&(t.lastChild.className="e",1!==t.getElementsByClassName("e").length&&(m.order.splice(1,0,"CLASS"),m.find.CLASS=function(b,c,a){if("undefined"!==typeof c.getElementsByClassName&&!a)return c.getElementsByClassName(b[1])},t=null));
k.contains=document.documentElement.contains?function(b,c){return b!==c&&(b.contains?b.contains(c):!0)}:document.documentElement.compareDocumentPosition?function(b,c){return!!(b.compareDocumentPosition(c)&16)}:function(){return!1};k.isXML=function(b){return(b=(b?b.ownerDocument||b:0).documentElement)?"HTML"!==b.nodeName:!1};var D=function(b,c){for(var a,d=[],e="",f=c.nodeType?[c]:c;a=m.match.PSEUDO.exec(b);)e+=a[0],b=b.replace(m.match.PSEUDO,"");b=m.relative[b]?b+"*":b;a=0;for(var h=f.length;a<h;a++)k(b,
f[a],d);return k.filter(e,d)};window.vglnk.Sizzle=k})();window.vglnk=window.vglnk||{};window.vglnk.product_widget_plugin=function(){var d,l,c,i,e;i={};e=function(){window.vglnk.product_widget_plugin.init={$:d,vglnk:l,log:c,opts:i};d.jsonp(l.opt("asset_url")+"/vglnk-pw-renderer.js")};return{setup:function(e,o,k,m){d=o;l=k;c=m;i=d.extend(i,e)},run:function(){new e}}}();